# IMPORTANT: This file must be encrypted with SOPS before committing!
# Run: sops -e -i kubernetes/apps/base/development/dev-pod/app/secret.enc.yaml
apiVersion: v1
kind: Secret
metadata:
  name: dev-pod-secrets
  namespace: development
type: Opaque
stringData:
  #ENC[AES256_GCM,data:NO9clt2rWTVFzWgiYo8j+tWpSTL4PWQE2GDLCVvylQ==,iv:rcOr3lhUy+PPfFeE+LXRIZ4Xc+fH0HawFuaW6v0m6v0=,tag:f5BTPEBtCUxf8OLg1rRaow==,type:comment]
  authorized-keys: ENC[AES256_GCM,data:48C4H7/hzIChmcxE6qLTaM1Pc05AjcOdLFSI20KXhXHMhsSdYO0cyqHADXBnNjY7USX/0IDnn3mvrWA2xz9Icli8SUAif37e1YoEEQpXVJhK1/V/sIK0P4fHrnTz8+fIYz2VCnJIbGQMLeIrCFFvWtyv5R2fGJV0PZOtu5akgJkd/yw6PaCXivyZ9Speuu1t+cUJ0dFWvWNwgmBaEMr2Jq0=,iv:njxiYjJ32Codrs0xUj3+fwgRxwHpRjSpLnYHdPFkgqo=,tag:cCM31DR353ru/VvZaBxlVw==,type:str]
  #ENC[AES256_GCM,data:2YAg1/3ws5RYC3GjLT9XbUA2N7kQdLSDHa1XAGti7B0LUHQeGyHF5T1HEAdPR3gjtYxnDxs=,iv:zHBEN8lxsXcDJInLqbF4i/cFMTH1AWNP1S4FBLPE0N4=,tag:nF5welqCiHEg2NJNyZ+HAw==,type:comment]
  #ENC[AES256_GCM,data:Jj7zUFZjqM//D2qLaFBjP+T/1qy1Zbd0o9Uv9ZM1S3dLooxFk/eBBxb7g8FjlvKcBm05hm5OeI9905h4pQ==,iv:kzAneEwPxOCpKdbwXJu1eWuifsBdYgB/va6GiRswBtA=,tag:vCdkKsWwS1mR6H58FM394w==,type:comment]
  tailscale-authkey: ENC[AES256_GCM,data:hCUc+jBUasVdfzbYpgS4jQpv1gru7u8Vyya6VRMu04ArbyORmJCMgO4DqTPDmZytUZqOBDTtcb5Dt49a3Q==,iv:kolPjjlK0oInyxnTreliUad2q/SzXG4RDn+mottWSOc=,tag:kxBKpp+mDIycAnagtbJESA==,type:str]
  #ENC[AES256_GCM,data:zSMvadq6x3+cNA5jdyH8cdKAiI7arGWcLv3DF8i4JJf4k6+JMvEbTZ1n6G1OBaJEG3vTgg0=,iv:Dw5Y1EfSURaY3RCTvJqMK16sps4/75AmXHqkHzYRZ7I=,tag:yknkIECn/uMiHC4sBV5Q2Q==,type:comment]
  #ENC[AES256_GCM,data:Ao6okgHQw00h9/bCmneZd1Ecxl5zzzt2mqVJpwRSvsfwzDWoX7gq72wsKScAO3ygK/AGUiZLGDvElCG7RbnKzzGrtFQ=,iv:yc475PVZw07rfLpFxl7i2epPAEMrv2xeXDpoBwKG4+A=,tag:2AaNc4ZtrGz8ofp91+51OA==,type:comment]
  webhook-url: ENC[AES256_GCM,data:JAor7shw2LlVhlte4sC5Y/K7fvryTHxatp9UfvJp7CccyA==,iv:xAm9v3kPmdwrSR1BJyH5YrXgw0psd3wiUN+VFsY9Uyo=,tag:lgxNGEZcsMaPDkZjtaqm4g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUXNHQUtlT0ZGWUVhdGN2
        Zm5hYkVqOUtjSUU5VWwrcHFWd0JPdnNUeWpjCitLVUdlZDRULzc1UlpGaSt3Kys4
        VitXM3pDOXlRenBGVTc3akhyT1JzeE0KLS0tIDcrOHErWGxuRTY2bHpYbTY4ci9l
        TUFmN2huR2FzKzEwbmltQi9RcUhaUmcKdPZtU6u+413yP3lKC5mRO6XzX9YSP7y+
        TTuQ9FxyR7FGT3/uhmc9wPLWhANDgN/+UNYmcg1HSNw6yDzBPvl6HA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T00:38:23Z"
  mac: ENC[AES256_GCM,data:zcIdwUSgYaUJrAoPUdfEmnQBwgN1ZQ5O3aGlpTq414ZL0x0xCMdUMozkDUtHtfb6zHYimB4bKZWC+JXcl12KoEpGQvxEg5BWpdRx38vG0B4wcetl71DslHvWywIkDPSAPm3cNKY4Ojit7MymlBYGGhhnLcZESkQtrIoM5+1w3yM=,iv:ZEEZ4pTOmy92OmQssC6aEijPV54QZS2gFadV/HvURt8=,tag:TjJU2DBtuLmmIq8VtpR1dQ==,type:str]
  pgp:
    - created_at: "2026-01-08T00:38:23Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQGMA8h3Ifv2u/MMAQv/ZmrwfNFnoQ4JuT3jdNMyv5gIAKTv8A2iYCNdiZ7OpIGz
        p/+kPYOwCucnbBLdCLT8Oj6EPdwWNB3hlGVbw93Rgr00VqezQS4e5TdA0tWaBR4L
        uqkW/hh4ag/4Te+sDnTuuofnGCFTkSGaXqVejqUl8J4vPnR3Lyt+YNGelTHVBqRk
        eYkTdewQZuH+szWiP+nC2B/RuStDTef72/qKV8s5N5+LRcgy41Hs2couoy5tWvBf
        5iVvr2zSP/EEszUDg9ORibbKvidaWNCHiDvU02zuy8Dwv2Fh1qKae/20E52pOcg9
        uKAkFUjX6P3fe++7Y7YA72XN9Vd1gpfd+mvu0iCORMpX88u06G6M1SIq9JSPpZ77
        guh3cTlyB/StHPKXeTA1Vg20ovnvQYSQUi75OYe4Q9DBj94B5yPHdqLGmKrpZxsB
        BtvIvvBA4lk10+Ln0hX+kvF6R+zX/qwJM2ZWaaurl1T2pee4HDUFcHN8Ab7Hciq8
        p7gnLfqGWNU8kf6Bevf51GYBCQIQGIXSY0MnTa8mTr87QyPKbBLZMiarhO9VtCzR
        PsWSQw8BRtsm3HhvY1xDHIbuuCax3Ofr2aLxikVEvgrnd574IMf/ZAw4Lb88mGSi
        19McF3qP1PZ1Ks+RYL0HJZws9Y0QWpw=
        =pC5U
        -----END PGP MESSAGE-----
      fp: 67AF5B5A73800481D8E41667C87721FBF6BBF30C
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
