# IMPORTANT: This file must be encrypted with SOPS before committing!
# Run: sops -e -i kubernetes/apps/base/development/dev-pod/app/secret.enc.yaml
apiVersion: v1
kind: Secret
metadata:
    name: dev-pod-secrets
    namespace: development
type: Opaque
stringData:
    #ENC[AES256_GCM,data:JC83HpZBcLeBofmDvpddQEu+INgLTUr+XZoDr0VqgA==,iv:5wqbB8xsJXQwy+C0zGDXRUtXANgm+sDVUb/AuGi2Tl8=,tag:OXSKvZCZfTD4VJ57b77qMQ==,type:comment]
    authorized-keys: ENC[AES256_GCM,data:8HfP0Hgzw1QMErwa6oJbAf7H+g9De+pPbQNpsHyMkEFMGOeopIEMPsQcChotPgReEDDwiciGC5iL6HE1sXCgsilQfEKsH0//vjlXy917Zbhl/vtNMZDC8gmb7JZaH0ipQKpOKzcZgyW1mwfuMQIfQDmmnAisjJcTXmhJGvEYAr+YsZ52y6tq/e7Jgzxk9svDdqRXQZMyBy+eevoNcC8ONME=,iv:AtDJGq0L+jtWES0wYXuZSCG7kgGNZky0+bTud3mXhmE=,tag:xZw6WGkhgkIBFSyoWTi7Mg==,type:str]
    #ENC[AES256_GCM,data:+R9vAPxbZp76T9qBTxtHhMxx9wgSGhD2kvnV7FOKeBqHBYvCKsOH3DF2Yhf7TOex1X7CJhc=,iv:91dVpbY7oyimAqtilYSD8ZqIVTKceyI6X1DwIkA4aAw=,tag:xYzyq0RmdSli9HxFj2Pn5g==,type:comment]
    #ENC[AES256_GCM,data:kWzYnXlb7rzucNHux3yVbu9+8G5cno+Ikb4sN1yuz7rN89QsLNvWyOYqtXJLmyvqWDEkooDdmX8euvfrCw==,iv:vCBmA5zkJA7fBElLcpQvbWHQiDVYx7d+8EO51YAkiT4=,tag:cAJ560MYG8w3G5SyWjMu/g==,type:comment]
    tailscale-authkey: ENC[AES256_GCM,data:R2zwWOd66ZWnbbPmybNDtOANWfZS1NlbsC83aVWvsiIb9r78Ojvn11vO2NRSeXff238IdM8GOPXM08Rj2g==,iv:RN+oD0Jia7xhvU0iel9pu3k3riuBicRvQRuRXoYB+z4=,tag:0wKj45nYcnjua4BfaIy/dw==,type:str]
    #ENC[AES256_GCM,data:/GaW+H+Sx0gbULKaNDu8X2jCmaRpCF+daQi9Fo1Jgd0zpKQ/q9zvSTIXroP9qPRaud6RScw=,iv:MWyY2mqN/alqCSazg52Ye2wKyq9bY7Y5DFcZO/FHzIQ=,tag:x5qzzmN1owpj7JWu8CAzVg==,type:comment]
    #ENC[AES256_GCM,data:m0RRLO85+1C9MVL2wRanO6k9FG5u5iXjtkJNWwow0JW4Mhmw/HUFem7v4ZYuZyizIStjag2RYkZdGmU+Z/fxvZvUHTc=,iv:ffuP14YbQlvcb6IPsLZKfDHFlqOcvbPcUjysWhA8TK8=,tag:ZstXQD7GkVI6CkDw+xnn9g==,type:comment]
    webhook-url: ENC[AES256_GCM,data:Pl6TJ4mcfgr5rhhLr39csSK5v9B0WzTTQ92491UPYmlArA==,iv:oJ6iNVTDH1CuQsj4rvX5xdqf2xyrwam3qwOeZWnWuNA=,tag:HGtWu8KJL46PNlF7Vm/WBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUVBydzNlZ0s1a1g1K3o3
            eFkrYXdkWmswR01xVDRCdWF3SloxbW5mbkZBCml5YklWSmVoRXpoTkI4SUNCa2F5
            NmxlTVBrbjNpNWFCVmZuLzZGZmEveUEKLS0tIEFrK1MzNW9zOTV3QStWdTRtbFNi
            b0VEck1sdUNvUmhyanU2T0w4YmdvR3cKjwmvG/Ila4Vt3LYdwS1hNRzV3+OcLjFY
            tuAeDREvpzLkLncVpRPO8bVhaUuEBxPE/e2f1KpKh3diFeS8J+rX5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T01:50:25Z"
    mac: ENC[AES256_GCM,data:BFRlgW1ulQmzYKdvz434rTbrMDs1gzb1EdSIcqsBXpTqXu3exOkgbT6dTdSFZXRc3PALg3j6woTNmdUPU2PspB74zgKz5vg741J/l48r5O+tIwDBQlzlmBQr6pg+Kz0WsJZkK30p9XZlLUJHPJC2yyU7sbSbZslWFkAkqnYkxy0=,iv:3yHzgP+0/F4lR5l0pTXOgfZY3RGuzbtCiHK1kDr3rIM=,tag:8CpeX+eGe3N/1wzx2AEq7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
