---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: hayden-redis
  namespace: business-system
spec:
  interval: 12h
  url: oci://registry-1.docker.io/bitnamicharts/redis
  ref:
    tag: "25.3.0"
