---
# TODO: Encrypt with SOPS before committing
# sops -e -i secret-magento-app.enc.age.yaml
apiVersion: v1
kind: Secret
metadata:
  name: hayden-magento-app
  namespace: business-system
type: Opaque
stringData:
  crypt-key: REPLACE_WITH_HAYDEN_CRYPT_KEY
