---
# TODO: Encrypt with SOPS before committing
# sops -e -i secret-mariadb-app.enc.age.yaml
apiVersion: v1
kind: Secret
metadata:
  name: hayden-mariadb-app
  namespace: business-system
type: Opaque
stringData:
  password: REPLACE_WITH_SECURE_PASSWORD
