---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: auntalma
  namespace: business-system
spec:
  parentRefs:
    - name: envoy-external
      namespace: network-system
      sectionName: https
  hostnames:
    - "auntalma.haydenagencies.com.au"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: auntalma-app
          port: 8080
