apiVersion: v1
kind: Secret
metadata:
  name: auntalma-mariadb-app
  namespace: business-system
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:ggr9yw5ttliwp6n4/1GkVPYJRNNcJbBYe11/lk8y,iv:tAh+ss+pP1JfMtXq/TrX0CNR6xx5xyHpgHQlkXJiIew=,tag:t8CdS/eRhNsbOAt4l3d2Nw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Uzg0VnNSbEo3amo0MFdU
        WUFHdGtzbmN5TUc2SWJVM3dGRWRvQ2xNcHhFCmtoUVZxSVVEVFdwa1IwcmI5dnlQ
        QXJaRDV6TWxsNlJwNXgxSHJGaTFMYjQKLS0tIFMxYjBCY1hhTXhQZUM1aXJBd0VQ
        UDE1MTQvOG1GWDRZbXBXTnliK25VM0kKhhh6SRoLsWe34aQs8gYrRyT2mH1L9edw
        wt8l/37q2taiWWSIiJl0kcNghZHESC8Ajr1zHYJV0h53dkhFqHnPEg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-19T02:57:12Z"
  mac: ENC[AES256_GCM,data:SpPdXy2XLNaq0MZeh/Y9+yrhrEIuSLEcWHmZmqK2zo9vCcQ2k8+3tPL+kCDq0aFaIwwHt4i33o7+wU3M2+iOT3SkktM0QLT+NPQ7rIcM3UkWR/c+NLH5IdQMN3+u5/7EYIpW1uGPkC7LDlhkzxeyDwyxk4dw9QUzrcvE5Pny6AE=,iv:krWlxfBtjt2kK1T5DUpfQZtN5jzBUzWb9BTfYRTX63k=,tag:+chetbKHT71yIeJhLHKXeA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
