apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  namespace: home-system
type: Opaque
stringData:
  admin-username: ENC[AES256_GCM,data:M3B4kkM=,iv:mewB/LRuMpPkD9LU9bn2vV/GK8aYHJHtDYuwvKu9JKY=,tag:yyGC7JT4C/nxE+Yl6iTpFA==,type:str]
  admin-password: ENC[AES256_GCM,data:8KDnjcVlYP2AxAlIhVNgnPTutSMlyc9lsvevVC6DjrM=,iv:+W0TO+TWArLMg5a555fqFHbKE34IDdmlX1SpxX5RysY=,tag:5DL51Kbee3LxchXlLDfaAw==,type:str]
  db-username: ENC[AES256_GCM,data:u3XBDY+30Eom,iv:nTgSmWIa5wfvTjdIcFcnoxhn8qYlBrXAanFi9ZDtZOI=,tag:BPMTK2b1R4xJMr9utAY6mQ==,type:str]
  db-password: ENC[AES256_GCM,data:/nWaf6Ll9oMaELHicGeORccjVYHowZdKWlkm3PPsrg0=,iv:k1KruisSbm0A955wwWwMUjYu2igIs0W5MPdz610I6T8=,tag:B2UjJyGAUbR0mEJer+WFtA==,type:str]
  db-admin-password: ENC[AES256_GCM,data:D1E23XhPy7rrPQ7LALk6IH6zV9oQv5LU0mBeJUQRRiA=,iv:gXHjrAm68F5DHmgh2Ypcrf43gWOxzp9DeZVYQx+JJvM=,tag:SieSyhc/Tk/bpN5sw9cqig==,type:str]
  smtp-password: ENC[AES256_GCM,data:lpUhT+BlBt3nU61X5vSQ0lU/qEQzjHhZwZSBY7RKhKVt8HSUghBvG6KAdDhfLwivN09eKbKlx7VYicurKrnzLs7O505/,iv:n/0RcVoPt5zwS1L6qEOYyHbGLNREVHg60Szz266Z3oI=,tag:RE1BK/lsKvtkTa9d6DbtiA==,type:str]
  values.yaml: ENC[AES256_GCM,data:Wt2lovydu4t5ZwT6GSQseFw2ZzHGFnWQX6D9qQ533cDWNIk8hA==,iv:TqYYIhAzjP0ahJoSD3twUI0c1q7/PaRAK+LcaG7zcPE=,tag:1rDGPagckcoF/Vu35SIdfg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdE0rUnBSbHZnQzJUZCtv
        bVVlNlgvRGllYkZ2bk0xTkhoNGFiWEQzZFRzCnc1OWtaaWliNnMrMmVkRS8zUThI
        VTh4RmFjRnNWYkkzRmUra0FkU2wybGcKLS0tIE00YWpWZXpoMnIvaFpmOERoTUtr
        dGl2cmNkZ0VHejlxa1QzU2tvMC9zRk0KbjFXO96IUx+/u6nMlFzHHQOLnWv81LgL
        UwRk1NGDic+2l1EV158l1hT5WxXF/PoLcmtFR5/fBuumySCKrgyXaA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T00:03:12Z"
  mac: ENC[AES256_GCM,data:v65vcO8Vao9jkmagZgy2exM0sT+tk9HmdkklUkArqhlW93FAPiTygx9nQxEfThMWcI2Bj0QQlXH0dPjpxcwxkm7NAcjmgPPBcoe8gic4k2pqYOfgb1VxYpI14RC9Vffik02yAehGslXdGHqNIhMD6roNyCnG6/XT2akkJPDU7TM=,iv:qyl3wpk3DOrhYua5t9qr27+2zZZIeNoeV6DSrSeDszc=,tag:shUS+Rot6+qLCoQvdxm6yA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
