---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: thanos-store
  namespace: observability
  labels:
    app.kubernetes.io/name: thanos-store
    app.kubernetes.io/component: store-gateway
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos-store
      app.kubernetes.io/component: store-gateway
  endpoints:
    - port: http
      interval: 30s
