---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auntalma-magento-apikeys
  namespace: business-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: auntalma-magento-apikeys
  data:
    - secretKey: algolia-app-id
      remoteRef:
        key: auntalma-magento-apikeys
        property: algolia-app-id
    - secretKey: algolia-api-key
      remoteRef:
        key: auntalma-magento-apikeys
        property: algolia-api-key
    - secretKey: stripe-api-key
      remoteRef:
        key: auntalma-magento-apikeys
        property: stripe-api-key
    - secretKey: stripe-publishable-key
      remoteRef:
        key: auntalma-magento-apikeys
        property: stripe-publishable-key
    - secretKey: eway-api-key
      remoteRef:
        key: auntalma-magento-apikeys
        property: eway-api-key
    - secretKey: eway-api-password
      remoteRef:
        key: auntalma-magento-apikeys
        property: eway-api-password
