---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auntalma-objstore
  namespace: business-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: auntalma-objstore
    template:
      data:
        accessKeyId: "{{ .accessKeyId }}"
        secretAccessKey: "{{ .secretAccessKey }}"
  dataFrom:
    - extract:
        key: magento2-objstore
