---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: auntalma
  namespace: business-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: auntalma
