apiVersion: v1
kind: Secret
metadata:
  name: auntalma-magento-app
  namespace: business-system
type: Opaque
stringData:
  crypt-key: ENC[AES256_GCM,data:1yzQ2EEw0tazj2S4oyUV1dsmBclZ9vk1/5XTy2um6u4=,iv:tQkBW3olriD6TF0+MpfcnbCMxpTzjN7IFpqN2IX1lv8=,tag:a/GugIFsy4fh1/dszaV1hA==,type:str]
  algolia-app-id: ENC[AES256_GCM,data:Fj103UgPeASlZoWrvRUiOy5Y4y1nC6fa,iv:PVbbyQZbgJ3cfm1bqL96PTL1hTBOxneQ9FZcHnwZ7Z8=,tag:eFxHMpJ5heTCUdLzVEZCeQ==,type:str]
  algolia-api-key: ENC[AES256_GCM,data:HryB0JpZYDine9AtQJg7uiZg2diHHV8AKg==,iv:2xzvmSxEvWq059Wh3LXAenXsh9RnV4FNpgym9gkUm2U=,tag:OYxmIxS3uk+UJssdz6pHfw==,type:str]
  stripe-api-key: ENC[AES256_GCM,data:DWnHZOOSYpp2DznsihTSXJqq+PYXFBgT,iv:2uy27hTC+8yjxv6V3i1F33hDY4FeJzyNxcVUXFPjdFg=,tag:vfzvx9U+ObfKLGtUuwtP8Q==,type:str]
  stripe-publishable-key: ENC[AES256_GCM,data:0JoeKHLZUpPks+JHwNYb156PGm/UEQ0WpHuAOi/ByAQ=,iv:ZLcaST6EOp5+bM/G3h+kJocyjOdW3j6i9wJujMY1xhU=,tag:Z4B736/cv8nKwDO0+9Zz+Q==,type:str]
  eway-api-key: ENC[AES256_GCM,data:Q6l11z3SHvLd40QDafxV4pPaUZ8T5g==,iv:Qu/4cA5Lmcyu+ZhbCEYsOKrx7yIgI2JtWy7mjZA2tkI=,tag:hXtE7+hiY2oDLd7+xbLHtQ==,type:str]
  eway-api-password: ENC[AES256_GCM,data:S8gKGgTS+lGWtsUYVnDuWICDcloJTPvMY7eM,iv:51wzaaKXEsnZM6HuZ3URMmEJyx4qiOkC3e88B9KMHf4=,tag:9NDLaimXN/qPJYA0ZsjVhw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbW03NzN6cGt2VlFlY01G
        SWxzRmdZQVZZUEhucXZvQXFPd0VPU242WkZzCnM0MGtvVEF3U2hFN0dVZ3Q3NS9H
        akdySjVTaVYyUVNHVW1ZVGNzSWVpYnMKLS0tIGs2bzA1cmkvSTIwVkFUWU82NlVQ
        M2UwbnR5L0lwTVM3MklOWEo2V05pWHMKZcoNg0Jg5fiM9MwqK/c7zm3kVxQeyObG
        mcIgLNr3jk35h+iFyqzq3qLVIALkSbuBul30ZXFlUqtoKoeGe1WWEQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-10T02:59:47Z"
  mac: ENC[AES256_GCM,data:axbVJ7oktInecfyYObXYLCr0wtdH6B0pLfHn0HdCNOECLyRW0Jr1vVtGwcexwMd3DiMB1ucEQ8pbkxXUlu3kmeNc/2C9A+avhA+yN7tzOOoE0WbqpszCLyr9gMyEFLmkECXees8ujz5qXru0eTAolKsVbiT1s3v3dFOZs6AruVI=,iv:PCq0XxgUecT3HHbwBULGMI0jUIgepU4NEfEpujdEcEo=,tag:yd6Zf6HmBCGaoIClHQMHiA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
