---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: thanos-compactor
  namespace: observability
  labels:
    app.kubernetes.io/name: thanos-compactor
    app.kubernetes.io/component: compactor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos-compactor
      app.kubernetes.io/component: compactor
  endpoints:
    - port: http
      interval: 30s
