apiVersion: v1
kind: Secret
metadata:
  name: onlyoffice-secret
  namespace: home-system
type: Opaque
stringData:
  #ENC[AES256_GCM,data:JitGVnXcbK7fHwk08pF9BZU8E4KjPMRT8SDeheXpg+mJXENh1hV5OEfg1pgZYBYqxa8=,iv:kiKfcoVUmNN5ojGZmZjzMH5RTvALJp0PTMbadQ48RK8=,tag:12XGVzGPwOzRNmaBrvHGeQ==,type:comment]
  jwt-secret: ENC[AES256_GCM,data:LXUFNZN+DUk9T2EvqmAWAV43rofBaDzbDE523/69Mf1egAGc85ZIMcMmFjfRusRyezuORnCYSnyWf4HMZlW58g==,iv:SNnMlkvFjXmjtBj8FPMwCsHbGwvtoH2cOHFLEcXewwU=,tag:N+C2GOhUhS3FFygULEJoyg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQ3BMRy9PcVdFWnh5VkVj
        OWhYMXM3TlE2WFlVNDZJOVNxS2VhT1UzQUVnClNEMUZsY2kvVTFUY1loTjh0MU1y
        RHc3d3hRQW1QTFRPdnEyTHBYQVpia2MKLS0tIFkrNXlMa1FueVIva2s2ZXdCUE1L
        Slp6LzV4QUJ1UWlYT0h0REUrcVA1c2cKeOMIbscici+xi7gE5i/Mbdt9mb6urNJs
        rpt4Clar15WzpyWLJESvVbyyHOx/m+d167n+7MUx9rZvorT9tZ1j3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-15T23:32:01Z"
  mac: ENC[AES256_GCM,data:tM4aSO7EN1sfHmrvrP0cpYoHvs0/EyPscxlHSiw03/nV9FV7m1K5iQK/mcRBbgUypihZB29bW+Oqt1ejR3UCRFEINN68xFvU6ckDZMMxNfvBZ4bKA8kC4zofxT3c0yjzb9Q2nXOHJah+XFjKoAVob42FY0WaVjdgaH/3+dbQ6OQ=,iv:z6yJUCp3z/n7+BqzXIWKG30QPjWw8USh7j0aJQ8HW18=,tag:XaiA0ul8EsGKGitoL9gUMQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
