---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: odoo-pg-pooler
  namespace: business-system
spec:
  cluster:
    name: odoo-pg
  instances: 2
  type: rw
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "200"
      default_pool_size: "25"
      min_pool_size: "5"
      reserve_pool_size: "5"
      reserve_pool_timeout: "3"
      server_idle_timeout: "300"
