apiVersion: v1
kind: Secret
metadata:
  name: cnpg-minio-credentials
  namespace: business-system
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:pSMUGqQ8cPb7cI0=,iv:a6ptj5qjv8EVPpXC8XsIPGRx2pA8wwZlzLbQ95nAcaE=,tag:dm665S/7h3CdoPINi0is6A==,type:str]
  SECRET_ACCESS_KEY: ENC[AES256_GCM,data:MDZm2whpo46WqTrT3XbvIae6jLdVTdfbrtdN2hzSZhnRxi7MFYW5wA==,iv:f8SOgf8JT7F62a61Ss1QCOg+CYzDwj2yoFYSHjkVUnA=,tag:qhU6CH6jZWdrN2IGAa9mMA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQV2lvbnlEdXdCcmI1UTY5
        MzNaZXFwS1ZjMkdJbHRPa01pY3cxZnU4N1FBClN0cFV4T3dzZWI1T1F2TnZyUmFq
        Yk1CQ3ROTjNmcHUwUDB3YWZYWC9JbWsKLS0tIDRwcEpwMWF1M01CUCs4SXVtZHZh
        VjUyV20zQmtYY21BTW9kN0srZ2dFODQKoZ2eKp/LcihmA3lDVYlApwNFCXKnxzpo
        MSzgUfcJmBcDJUoo9VmJtmSVoNCfIy0JW2GWZL2cG52BlP7aOgfOOw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-16T23:15:22Z"
  mac: ENC[AES256_GCM,data:LcwzsoJTmZL1lS89GOB1IWoN4e3ofoEsQqRUnqRN73qB8/YGHOA9T7VwDuNUeLj1EOR97TWPVXP6FdX7UYZFuTt4frlljGpprE6HkDrNj7qenPbYG4n48+f50U5376HHzwdbeimBzUZnuI4GgZVi+lrCL7YqQfQEShQn3NzP7AA=,iv:lUxJnuXkOZGTVGgN05kYSTXyH3fyCEZcJ8JCsXptcMA=,tag:hVruduDfG8avIbCgcPjKLA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
