apiVersion: v1
kind: Secret
metadata:
  name: odoo-pg-kagent-readonly
  namespace: business-system
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:6Hx22SzhlhiTCjINcrkD,iv:CyNpxLyn5dJROBOD+qr8jpaPuUv8A41JsVUzoudeCZo=,tag:0HuBMOcpFCdjQA9DHwUvXA==,type:str]
  password: ENC[AES256_GCM,data:ULVZo/1o6NJ7fqzHjeEL+dK+118BqRku8PjG/waIB8U=,iv:fx1h6y4+F/jy2YQB/luO3vNm8ZViXxaz2xK35OQSvzo=,tag:sWO4Wf2Fe8A3pzyeZcDl/w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRanc1ckJuVWpMRUtISTds
        ZjN2ODRYczdMWHc3MUllMXk5eDhkV2ZRYnhnCjY3YUIvTXdIUUlzL052b1J3M2tt
        YXVtZ2pMM2hTVVZsU1hpclJKN3lMQlUKLS0tIGJYWWxld2poWU5ZZ0ZqbG1LaEF2
        WHp4MlRWRUpsREdUSFFzbm9jZ1hEK00Kamz+TEgMMthWTAD/6tABSxs/sb9P26Nc
        REgN8tdojhteMOjRppg7z+iAx4B/L8UkmGQ3x66xtrCSSnpYf+w9UA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T03:30:21Z"
  mac: ENC[AES256_GCM,data:UfRyKrdmoKX+8yj4FKjZHAV5N8gZgHpxgnS2AtPY1CUEh6IQBu1toGJMdAD5iom8F5Er02ExCwH7pzrV9GRucCTektHwHNniOm2ikLVRgNAnYY6Qli0ipyW58rE/QydSBfpiU4dWEOBRfU6PLY5SiL/4b9z2bnVnO6gkqmlQ3rY=,iv:Gk8GSQYj/HBZ9FRgaoIJvUHelDaCHOcu9nk7Sq/fMJ4=,tag:Kdbc3acaSrAdS5HwCpbgoQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
