apiVersion: v1
kind: Secret
metadata:
    name: odoo-pg-app
    namespace: business-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: business-system-staging
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:V84YkA==,iv:H9yvNL5lw9Rxb7f4qPy+rq6ytPGMxNRrVcPAODfWP8Q=,tag:WVmK6kUVWWjzrlUPyBqLQg==,type:str]
    password: ENC[AES256_GCM,data:Pdfdv5kh+sWlKrki9YeMJHRWiMhyDwfWtk2wXWjRl2o=,iv:/B2XQOC5tbdgYZYI7oB6IxcXa363vEFip7SfIc0NzeI=,tag:R5KOK2ENDp1/NIDlSt8WVQ==,type:str]
    dbname: ENC[AES256_GCM,data:W9nL4Q==,iv:OypfFdF7Y6UDFYgMXw/AvgRaVyv/AzfK9pz9ofoOQzc=,tag:jQsPGCTdrTJsJtoPSSSfXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraTF2MkhEM0Q3VGIvQnIx
            aGNERjQwWmR1SElqUE1rTEhJcTFzSmFtalNVCjBXcS9TZDUrUzQ1L01ZRHV4TThU
            QWhIUzBFN2xldkZTem1lUGYrVHhjVzAKLS0tIGhrQS9NTGs2YTJWT3dJOVk0dS8v
            a09lK3FETTk3aVFxa3MwWG5Ca0NyTmcK7kRDazwAkuxfntwOtm3tTYp2Qkz4S0c+
            UGAKQqYwE60aW1Nhj5y/yvagKLQHt2pFLONw1/eEa4uQ3NbFJ+EqXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T01:50:25Z"
    mac: ENC[AES256_GCM,data:+GRjgl1m/qR02bVlt8bG2gO08bxbPQbM4H/g9faiXsB8kbBcbO8GpTVTi/ygNo9XW4cBWucgMKRdPXL9JZTT3tTDPjr9MrNEtv+RA3U2O/BQxEpTPEqq9l4z2oDazGd6NaKMqFSkvAbqSxmtWBEhWzeXWmPTFUiWVmlt/0u6Lfo=,iv:Um324DCeD5VVuA+MKF+JqFwdez29iwULLIMI1oBwlMo=,tag:9qVpUOfP0YapFbS49RxcMw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
