apiVersion: v1
kind: Secret
metadata:
    name: odoo-app
    namespace: business-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: business-system-staging
type: Opaque
stringData:
    POSTGRES_HOST: ENC[AES256_GCM,data:KOs5U/3XY02aZQeiACgOoe4R/0q6nezTKu4krR3IVjJKMwr9VHOqexcdPAI=,iv:osdqdZkfPbQsFL8pTLWcCSOaxB0mfn2SOb2YIeJlp+Q=,tag:CQW5U0zp+1l+dnsqV8XCow==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:CwyTUg==,iv:7KxK0vpvnwPG+0ipSe1Y1rosS0TGoGaOJ3TqeualPjc=,tag:zdKiNW087vvs5rMXK69xwQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:CKDfqQ==,iv:eIGWUTHtPUzeKF5F9lqsQoqzdOZlCHrK8TPKfUeNA/8=,tag:Y8epuograwNos3l4kpvXPg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:TBXU4w==,iv:rPsxGesCDBD7tDgyAHMnYmUm5faBUL+a1Pdc4bs1cQ0=,tag:SPKjllzMCG1iGvtahwcfXA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:/VkYQYbYvDchoDk+gLquICkP2nF6SzKCD20+pHuVMO4=,iv:lkDdjUU9jv3mMBfd0Zq7GcSsSz66SOo3oc/okDxk2KU=,tag:Gvcyt9d1D4iCYIPoNfSYhQ==,type:str]
    ODOO_MASTER_PASSWORD: ENC[AES256_GCM,data:ttQ3+JAxh21gAmh6251TSHrIuF2yzuG00utdPTIqYlM=,iv:prf5eHZ6mZDeax76RXVdBSozvCBUvpCJk71Nn8+V7kM=,tag:T1OASiR2WrDCVkLWZUC6Fw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2d3VMSXZFTWFQaE9od0do
            dFJ0MHFvbVVIVzY1RDRuUnhkU3VvTXgveEU4CmNUNTJOa29PekJwb1l3UWhwSUw5
            MWRTNzN4ZDczaEg2bHBoRGswaWJHUjgKLS0tIG1YYnh4YjNIQVRscDFRNjBrZDBq
            S0M2M1VjOXVhV1hMQXVQclAvK3h2bFkKp4CBBMbUkHSaK09Iz/X8s4M5IWdzpI66
            he8YJlZwZtajGSt8ka5pMGsh1A07Yuq0BUOR5l2KQrRhwKm03WtOxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T01:50:25Z"
    mac: ENC[AES256_GCM,data:rZs4pjpLkFr9/kMBC28Ac2kCKySQ+s4MJvByhV+eGbj0JJAteiU5Rm+EDMJYeKUL6sOYBfNvOqT6zuUWVHRY0uXrxDxt1JzqrwH0/Bnz+KN9pjbWhr+aEPJ37ovkHiMjcVPOTWHiXga3VMSjxxXsGg5t5tdXe0kfMrVs1OjuWAI=,iv:g4Y5jYNXwSqJTxXZxX7Hma7HtDeiK+v8D60/P7R+VA0=,tag:a5CBJZn2wM57asIhaDGvLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
