apiVersion: v1
kind: Secret
metadata:
  name: odoo-pg-kagent-readonly
  namespace: business-system
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:wnX5aYRGWnN0XUt6QGEG,iv:os7e31n1nsEZ4JOSCkFaBUKt9oHEDir48eiuvh3moso=,tag:xNIsisCxZVC+caxfXQa3Xw==,type:str]
  password: ENC[AES256_GCM,data:ycjo+p4agURUeXktNtyL2/txmfyhBAJqJxc6Wg==,iv:EOWqsy6bS5fzyIGk/ZU8M7et7JSu+mMUGoxFJVyFv1s=,tag:wyCovXRWmh0LBn9JRIqOPw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQlJPL2NWanhBM3lSTkRk
        eGlWOXVnMVVxM2xUWWFGSWhBekwzVnVxS3hvCk9kcGgxY0ZxaW5CQVNMOXozdEd0
        YWZSeEg1a3BZSElJZE5Pejkzd1RWMkEKLS0tIGw3N09ITGllTEwyRTZld2RjWHd6
        V1FXcWtITjI3NXZRV2ozcVY4VllVOHcKSxdSU2+0R+zUEQc5qLAro8+S+8AhfOEC
        4bUbwYpFb4eTcZDYI5yrLUFfgtGiclCOZH0vNb3+1UDrssgV0RcKbg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T03:14:17Z"
  mac: ENC[AES256_GCM,data:UrstdsyfQZBT4GAul9VGffgq3iFtFjpglXhH0SZ/8dwRrp9j3qz0+3KUx3e+1TYYPZCJS+n3vfk8Sn5M10L1LkBmxfPOGzVlJAmdkE1tb44za1XMMKVGkwPxo+/6md0gCcziDHh9yQRUuNVld9oIlZo7GU+/bD8qaE46k8JfVQs=,iv:MEf2g65s1NOu+MBUSi8Y6VOFM+RhcA4Rocmds26iGLU=,tag:t3ttk4LYrlZn9/qP129qbQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
