apiVersion: v1
kind: Secret
metadata:
    name: odoo-pg-superuser
    namespace: business-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: business-system-staging
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:cGwSZqN7onE=,iv:BGQCmW+2pdaqqUfsc8HoxKUZ8YMo6CJOJBmccS6GMDE=,tag:4xh48Mk3JvH+d2xGhH/X7A==,type:str]
    password: ENC[AES256_GCM,data:zUQIxJSh0qQBG0vYVvverVRjOJHFfMIYrk6PBXp2D2M=,iv:9NJLOnMNCDJVZ/Y+Zjpqmj06ebD04FHNr+rHwVEYXsI=,tag:kWj2GNyBQWWr8fESz7GZzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVFRNRVlTSFQ1bWlPNHJG
            OXY1N0tNbmVRejJrUzlvblNhWmVEZFpvYnkwCjNXSWdmcWQxZXQrSDZWdDBKTlUz
            cS9hRzlsZ3pSTXMvczJOeWdJajlhdzQKLS0tIFFvYVRYMG93c3grbG5YdUNjQ2RL
            cStTTHBsMERCWU9GRU1GSXpYNFNTeDgK54cVr+k59p6kh5IbUnPIPUDegzVfR01G
            4meOtQ6ef7FxXtLKbl+ltJTzvckLYCqBDZGppx602epWoSdKI0ZqiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T01:50:25Z"
    mac: ENC[AES256_GCM,data:vDZj5Wtrkzx/Mxx530CAPyrviCiaE1oeOC02pDd3pjXY5VJeX0/Rpw7/JP/QvJX9p29ExMu5kdDi3yVIVAxuiksMqheFovbTYQMUtYwLVYGCEYrcq+GR3yq0OWlv2o2gXOMOGlim9UvNMDzZZHUZEi8tse4P5D+wcSX0MgL1d8Q=,iv:YL74wi6+GUrbMjk9ZIw/gMZcubVXTiFM8P/T+zE9d+8=,tag:XQgvuHayKSK0nNi3s3rBHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
