---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: bitnami-elasticsearch
  namespace: business-system
spec:
  interval: 30m
  url: oci://registry-1.docker.io/bitnamicharts/elasticsearch
  ref:
    tag: 21.3.26
