---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: label-generator
  namespace: business-system
spec:
  module: http_2xx
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - label-generator.business-system.svc.cluster.local:5000/health
  metricRelabelings:
    - targetLabel: service
      replacement: label-generator
      action: replace
