---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: odoo-staging
  namespace: business-system-staging
spec:
  decryption:
    provider: sops
  interval: 30m
  retryInterval: 1m
  timeout: 15m
  path: "./apps/base/business-system-staging/odoo-staging/app"
  prune: true
  wait: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: cnpg
      namespace: database-system
    - name: envoy-gateway-gateway-api
      namespace: network-system
    - name: onepassword
      namespace: external-secrets
    - name: reflector
      namespace: kube-system
