---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - externalsecret-ghcr.yaml
  - externalsecret-backup.yaml
  - secret-reflector.yaml
  - secret-odoo-pg-kagent-readonly.enc.age.yaml
  - helmrelease.yaml
  - ocirepository.yaml
  - postgres-cluster.yaml
  - pvc.yaml
  - httproute.yaml
  - securitypolicy.yaml
  - backendtrafficpolicy.yaml
