apiVersion: v1
kind: Secret
metadata:
  name: odoo-pg-kagent-readonly
  namespace: business-system-staging
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:j/ApiQhQWtoPA10NRXbd,iv:BJC8X935UCCRWwZWjHqtc28+xc5hCMH7jRgTRGE1Kqs=,tag:le0Cgv3rfmrAeNmkPeLMCA==,type:str]
  password: ENC[AES256_GCM,data:zc0fNwhqEfM9qrPQ0hERtXXJf46vf6D6wlG8kbVSVg==,iv:1X79N9z4t4aFoU2rVB3fTBbkYZsWsqJDPjfSVUy+rMc=,tag:RIiExefmDOhA4ltxQg50nQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMXFibU1LeUhFbmJWRUNM
        THkxRlFpcXNTMW4rWlRVTUwxV1JwTTdIa0dNCmlqYk03aU0xZEFNdWJFelFSZUhw
        N2RaaDRKZXpVTlJ1M1pnOE5GSXNYZVkKLS0tIFhMTGtVamhZSW9tK1FzOU0zNjQr
        YmdLOWpvbHNET3hGbzRIc2ZuSSszeWsKNDAZrDG2O/a//tyLENjSIHYspGiZ7atl
        SIVVaDHbaKgF5t8FF8Ag4ME6l7VK/bpIwom5ITyjaZu7pbq/kdQddA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-11T22:50:23Z"
  mac: ENC[AES256_GCM,data:Ea79VGMqn3japY1o4NpI8ZKZd0BhbPDfYW+MH/+pr0vB9lCbPTzRuvPHqc0WktDn2W6bgo2/Tsp7Q0OdhFPwDiKHL+dmqg8Zn/myircbh4wOxFJExn569OC67GCqfmM5lSfiDW8VIak91PSsUOR6xFL8VaGj0dB4BXeaNgHdpss=,iv:mZ2g87lfZ6DWcjNqeeJeHL0WpGTNzDJfKpOQmzYA8Jk=,tag:11BcyswHz62jJHQiRg/XMw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
