apiVersion: v1
kind: Secret
metadata:
  name: cnpg-minio-credentials
  namespace: business-system-staging
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:wmU7Qd5t9WjXexs=,iv:YEqoqNK7K03f692rcWvp8oDy63SH19AFpYoW/+W/dAE=,tag:Lt1mBb8O9bynr5ZMali0Zg==,type:str]
  SECRET_ACCESS_KEY: ENC[AES256_GCM,data:JAx27IBRbAenhYcvZpwbSE2InZaDv6ZhGjeURSqh0CIs68sD5uln4A==,iv:lWBehIyQN1yhhDQgeBgG9ncBq0mirrnAumgsPnDosTE=,tag:xFFAbDQg/Btc+dlaz7RVcQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MGxGeFFBTVNVVkNEa1Mr
        ZjZDYnpmSENvbmhSZVROM09YT1VtY3RYWnp3Cjd3ZG1PQ2t0U1EzMjkrVFJVOTE4
        WkFmSkRrY2tQR1NZQlVmWHpvM1VzaWcKLS0tIG50MjFucWw1dlJlaWMzK0xTSVoz
        YTBWdTNvQWhoT0Z0SG95eExRZWlGNm8KVmIbVve4Z2XlZLomIGW/DlS5JrS1yHSS
        46gq70Wp6kze7d5PFzRH9y9ER46aKFPbLT6BwhvpQK0F9q/GNWsJrg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-16T23:16:27Z"
  mac: ENC[AES256_GCM,data:YBmnZ5EUTRauzlg6JHaD+wfY0owaiEpwtMBzsvqqhjXQk5jtpEonTIZ2UoXKwZqokcnwm1O9l9LPdWWf9mFGn3TsF3YJObGMqrr36L6c+nmZQEuSkgZ0bxz7Vk00bDPrHzXPWdcN3ZwjhUVsWX4d587RJsnMkgdi4Nfvr82YCpY=,iv:dtm5kLWs/X6kYMHMwELsCV/xxfRUUOfXUfcozHVr3JM=,tag:TkPGPmvf4tiAm634QC8yag==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
