---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: onlyoffice
  namespace: business-system
spec:
  module: http_2xx
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - onlyoffice.business-system.svc.cluster.local:80/healthcheck
  metricRelabelings:
    - targetLabel: service
      replacement: onlyoffice
      action: replace
