---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret-thanos-objstore.enc.age.yaml
  - grafanadashboard.yaml
  - helmrelease.yaml
  - httproute.yaml
  - securitypolicy.yaml
  - ocirepository.yaml
  - scrapeconfig.yaml
