apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-config
  namespace: observability
type: Opaque
stringData:
  thanos.yaml: ENC[AES256_GCM,data:aNVnn8Yzf9Yj21Mt4EzvUK70WPxtg8/W4H9rjJoHLBl5WYdIFchK6aZgPy75zhhplvik7jSLqOwHznYMCYAJ92TRw5/BPUVoveT9O/fx7qvX9Rk1jIfle/SxCYp9og6XoNI/T4MES7s2VD0Z3fQSXiXsnFhaSC7whtISL+254GyPRu/2KiuMYkR4Kyk8AIal4SLysGJZmm1sXlth6sAHCm0E2XK6rfRXrE8cU6P+99GUn1aYv/KxCh9vMwA30uU7zJNu9t/35EF5POJlJ2fz1dMsJp7jz8CUZEMNOK28X8eL9mwe/FfOqWFVok9bOoZoCrly7j7WKVrDEgVI3Q/wXOFDeTr0ceoEtcsHb0tmZX9g64JcNdWEbotER26LbU1BfQfAEd7cNXeyGY6tGUfzIApbpw==,iv:w5gDiWgMg4lXGB/Tzubkl1KDteZxQaem/0hmbLzNOSQ=,tag:s460sPg8hwK2DWbuFSfG3Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxOXIwVWNVSDg1MWZOWTVQ
        TVlmMmtPaTQrMHV3VVdCZW50VE9tVFNJRFZnCkFSSTFOeGc3OXBCbEE1bjV5MWwv
        eFZERjVBN1o0N0RWalk3c1Z1TjBZa00KLS0tIHM4cjBWSmpXa3VaS2g1dEJJeXJY
        cDg3TFlLLzRSMUxNVnRxSFhWNE5JREUK8nn4tQkdO+SW5f60leAtP59NRjsXPOe6
        skmhJrVB50hK/hMCrIr8xQtWRRVzqZsD/yQr1f1+WPv/ffpWfDpDOA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-11T00:18:40Z"
  mac: ENC[AES256_GCM,data:VtLomlgjwnU0oE13nd52EUadoZoEpGi09OYU/PqT3YPaa8ltlMx0GQNtttjXQwPuBcDGqMIe3ZjDaqO7CSvD9XtLmzTeScb7PbU4YO7Fd9xJ7o5B2QTQLQv+qdBA3KwtLIYAe9Uk20EL/BWRdM+w/ZvIw7I3V7w/ODKiLgrhrnI=,iv:kIB41fD0Mml1T5rkwv9Y00afAqyPIrxbgxSCaKJ2cPE=,tag:VhWwCrJ8pLnlAa8PLr37sw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
