apiVersion: v1
kind: Secret
metadata:
    namespace: flux-system
    name: cluster-secrets
stringData:
    CLOUDFLARED_TUNNEL_ID: ENC[AES256_GCM,data:5i92ljIXVG9XTgSgT/zF9e0USyX8XRA6nSiG83UL3qRojNxS,iv:mu8fHXk7mkgu5xXfE9ECrphnQwEwRSQ/9eGvEhBnb10=,tag:qRJNjsOGs9LdsdeXVknTiA==,type:str]
    GRAFANA_ADMIN_USER: ENC[AES256_GCM,data:2PJ0QnYjUA==,iv:CdByJks/vFgsHbS9uGHtC9y1aiRzKvTe0VFy2j2JGq0=,tag:s6oJPVhaQC+fdl+wEGrsIQ==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:HPp34U8uwZHQ5s05anDrbQ==,iv:6mISSmME0IdMz3gylunoTbUx8ZnCzjT0SwYx4Rhx+OI=,tag:h2LqefG4qK2WutKfOw5Rrw==,type:str]
    POSTGRES_SUPER_USER: ENC[AES256_GCM,data:qMFGIEpZv+Y=,iv:KsXvJ2qyeks4qPTZiB1T/EHZscyaXvsfkdFFATnA4zU=,tag:Ma40Zxjy9UBn9wLN1b6aDA==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:uOxBxZSIlFnXSTf5fbi6Xw==,iv:EG5KBv/FEmqwU5x+cGWTwU7bj2rYrdE1pwI1Ilf5Zy0=,tag:ceNw/5amKXloXnfBujcOaQ==,type:str]
    #ENC[AES256_GCM,data:FUX6bJWnF+HUbxXCmOQDgxutQ4YGwucUCzWGkKc=,iv:pKcZkSvobysJ7Da7fddoFba2jar9vxmbiM8AC+RQPzQ=,tag:Q7O1Qyqq71uhGg6xeUL+IQ==,type:comment]
    PRIVATE_EMAIL: ENC[AES256_GCM,data:Xb3tD8a4fsIAqcanOrRkKQ+Yr8xcRf1n92Wl6Q==,iv:cojDgLrvgBfDg2YrYguwbbvUzNPrldhzSG04LfG6WmM=,tag:cxdrPMrCzhZxPkDPM9hHcQ==,type:str]
    #ENC[AES256_GCM,data:gSwYsthqsS9oapWaCNbcRRaH1xaSOzzG23jCXn/1X+37HssMfRX9z3eEyKVw,iv:qLDd93LNBkj9T1Jknruv5KabkhmYp5uPy6Ii4p5D03k=,tag:ih3ZQaVuzQ5pAwq7A+hHMA==,type:comment]
    DEX_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:01AL7s0JVIxaRjQ0Pw4lQQe9Jsc=,iv:7bQlo4+l8GUUaHsjMXQIZEanJx1hsCWs3/gkAkmzREM=,tag:8t8YIm3bZzZXNc6WYhdwlw==,type:str]
    DEX_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:PLcEDWlJMq2emI5RzrwVcJ4Riuoa+4nX7vHEKl1BoJPgB++Oy4f6WA==,iv:bnlDcLTEA6PwOFht9TUdlhuNR8Wej3KLTtT2AXEXiVU=,tag:RJ/qcBStSqkmfno5G0a7Gw==,type:str]
    #ENC[AES256_GCM,data:KBFpLZ+8zho+VE13yobEWVxN73Vy1prM9h8UPaOiAb3VH/QsomcCPgUjm73GBtM=,iv:WqgcqT1X6oECVBBGcn9wuJpfQ6f8M64RbW9ByOgAuus=,tag:bPUBpnce30e/mB7R9s6NLg==,type:comment]
    DEX_GRAFANA_SECRET: ENC[AES256_GCM,data:ckyk3rdGf8eul3AWshLsN/CzHOu40d/fgeu6CURC0mVTl+2aE9/IByqFiux3YxvMHbc+uHcyBxpn0KVKp1GjmQ==,iv:wZpLoG4hKgF8/0wKhhRzfrtEmNl1fXtaJB60mQBh0E0=,tag:uvZ/nqMGEFru6XqDAFEyMw==,type:str]
    DEX_LITMUS_SECRET: ENC[AES256_GCM,data:/zImFpcw3wwfCnaHwSes9nhP/8/f9D9P9udNzBVXjVmdWNhu1Tw7yLyJQsAbInQPfP73k5fL35P2oVARBi93,iv:lGZGg8wZV0D+eg/ueMlBe4WFT0t7j6HA9MQusy+rNNM=,tag:XHYB84zovHOCpvE3MWq1Dg==,type:str]
    DEX_K8S_CLIENT_ID: ENC[AES256_GCM,data:2ijKgzYlIX5WuRd3/gtJWme8Jhb8,iv:S2q+s1d6k7mSjqrW0c7ivetHg1HUaLBjXuRKc6g+2wE=,tag:+F2Kd9teXtq5oryrhF0Jwg==,type:str]
    GRAFANA_AUTH_GENERIC_CLIENT_ID: ENC[AES256_GCM,data:kQfBFgyu0g==,iv:ikFEpWSB86cxi2vge1MeviUz+ngT3IbJe4Tq45bgCj4=,tag:6AUfVy1DuEaniTMTug2SNA==,type:str]
    DEX_K8S_CLIENT_SECRET: ENC[AES256_GCM,data:uJ7MYhP/jfH7Aa76RmuF34AVpNfAcXPnXzAuGi96E5YOGKORB1HMk40k5TrVDLrjNdSD/ryjnoIIE3Y38D2tNw==,iv:dQ/bjHyrjiG0KicT1mY6PZzq1wYNTcuAou9z+WhJBMA=,tag:gRCFqI00R/JD/Kg1SDv2BQ==,type:str]
    DEX_OAUTH2_PROXY_SECRET: ENC[AES256_GCM,data:KJMK7XyIQkjxiopJuP2O2CW5UtPmVbzaYtmtxPL9zDpotP+ZQi+0ohO2kX8y+3iQqTkdIQCkIJa+n+7kZPG3vQ==,iv:zA16huV6j9wCTqfmJTH7bexpAQbVv+0CHhVx6kDf2Yk=,tag:xnvxNIyGXEoy7Ll0Qzptmg==,type:str]
    GRAFANA_AUTH_GENERIC_CLIENT_SECRET: ENC[AES256_GCM,data:9cHNZOARaT+l7y2A4zxTnYGhAuogq/q0PpwX7RKDYHboURvHl/AQ/wtlsRszbH0OyfP8hrdnx4seNlRxULozBQ==,iv:zuf5APAErKoIFHZi0DnFfAD/LIr14+EpBgmE+1zuil4=,tag:xUnMStzL5y6Cq5lpvWLI0A==,type:str]
    #ENC[AES256_GCM,data:UDck9k6h6F388kgbc8NW/0hDi8QD,iv:YDFEkwax1FW5tPHRmuLshhFInQsGOhxPG6PFwE+d42k=,tag:AIVTOOPeH8yyb3UzCXFgTQ==,type:comment]
    MQTT_USER_USERNAME: ENC[AES256_GCM,data:uhg6GBkB,iv:IrqNnPZi63588FEhsLGCh0t+HYwNwlcx3q6qLHwICnM=,tag:cqOPzEfQUKgQoT1msq9XNw==,type:str]
    MQTT_USER_PASSWORD: ENC[AES256_GCM,data:6DV3KcLX2tGyWpb0Ug53IQ==,iv:zVis6AW/eL/yR3IwcIZeWXD7jYQeXx4PTUL6T27TDmo=,tag:rbzC8QHpJ0dqkrDr/D9wIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSYklMMkorMVVQZitDMHRU
            RXU3UUNGSW5mTytKUzZnbjhGUm9wYUtHVmgwCi80OUlCTnVGN2loTWNQeHUxUWlF
            SnIvSkN5akZvcGtrbGRLY25oNG9SR0EKLS0tIEJIeGdCUzQ1Ymd2VUFSOSs2LzFu
            aVFpK0F3d3ZSYktaTE53dU4rRkM3M0UKC5yUh0Hbha8iCTStShw8DNHZ8Al3JoQe
            F2gmQzzDuDKZNAPgMTEZzxR5Ro3izTBUkICufThkaImVRy/BOkUIuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T01:50:25Z"
    mac: ENC[AES256_GCM,data:UjvnHcscl3C53qRAxxh0kHc/a3V7Npw9nDDQT0g9y64Wtm/DZCpS6SQD9dtzN19narKdX17etBXythguhcRpArcrsfEeHXwWpe4OxEsLf5UOvkoZlMCMBTkk89d8YEWPRuWmnvi0Aj5KL8WIesQKfPVffgWIjPTgJBhFx5bsyHA=,iv:hb8hVGXA1cbWkwmHWdQbNpVcK4FMSiutszu52XjSLyM=,tag:NxVqGNQzp+gPhFaB2ldNVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
