apiVersion: v1
kind: Secret
metadata:
    name: github-auth
    namespace: flux-system
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:z4RRPj+S9Y+bWuUUIjWpLbu3quUVBZV3qe0AISuoS7pFoNJ5GoBMOUIBoDJHKFQ6fEbfZw+DsJrUho6lvVutv/7AgduV0kLU4WwE7OP5R+vc2c/e6ilLziGs+179,iv:MNuXhZkNgSZ1X5KVs5gUJkEsDMBx0+yaiAo37VpgPU0=,tag:5CM7vSf0IA7B0f8Oo4xhxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcEFvaDVpOWxpcmhpYUNo
            SXArcFRDNEdOeGpqVDhEN1FOcG1PN2xHNUZNCmVRNFdGaVVHTXRQSzVOeUp1Q0VH
            OFB3QzdUa1RjQk51N29LYWFPTkl2TW8KLS0tIEhQUXVUOHVidWJVTHFyYXpFUCto
            aEI4NWlXc1A1OE9teHhHUlg3WnBIVjAKql/ekBUMMIr92f4fwbT8q65ZwWczWss5
            96xwTQwg0GXkFsjYx/IdVNUhm777Lg2vJQ0eY6//n4s1YiPLWiGJQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T01:50:25Z"
    mac: ENC[AES256_GCM,data:LeeyEOmEHoTK/hRhVogM+cSvld7Q0gGu18pedDsdR48wBsdYWZSCxCdy25b/mM+jEAdKQ0Sm2jXsNPosNg41laY9wsR4x0lX47MNfE41CLo0xH19kdJTQnb54JqM/ZazmWOd0IsjCVNma6Cg4xt1GWDDyCeXYvPJUooupTqvkpY=,iv:pC2x3n3InyJIt9EAK4qn53sU/lrooyj6tLD17zqEw0Y=,tag:IRDiGyZsQUUlMVV7C18U7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
