---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.envoyproxy.io/clienttrafficpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: envoy-external
  namespace: network-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy-external
  tcpKeepalive:
    idleTime: 60s
    interval: 30s
    probes: 3
  timeout:
    http:
      idleTimeout: 3600s
      requestReceivedTimeout: 10s
  connection:
    bufferLimit: 32Ki
