# n8n sensitive helm values
apiVersion: v1
kind: Secret
metadata:
  name: n8n-values-secret
  namespace: ai-system
stringData:
  values.yaml: ENC[AES256_GCM,data:yMtVZPFa5fYDXAzVuFHRdesGUlfnxhkAhqF3uuEg5cCHQPhYaE+l7SyHgLXiH69wmfLi0Ce7qPDQO/W6j+tQbyVkRUUXLx1g2DqzWuYgRpxpeA==,iv:Q4oFu80sgMiVRY9wEgCBcceHP7auDcDGq+b2D3t4jas=,tag:Vmffphj5ieyEjclDIt/ZEQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMM1ZCMlE0bWJxOEx1NkF1
        U09WYVYwYWJrbUtEK0l6dGdrckNaejdOZDBrCk1nbURtVlczNFNzMk5wV1VxYWZD
        UXdqVUdudnlyQktINElsUHZqbGI2dWcKLS0tIENhcTFpL2hGdFl2amZ6TjFmdWxK
        R2VDeCtQc2RFVkUzZzRFbTR3TWFpNncKw0/5NjvR+UFpENWJWPyqm/ih2xnPi/BU
        GyFcJcuoTyzOqjuWwxgg/O9DZF5VJTOr0Hpr/XOQcZMAz4yayuXwsw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-04T23:45:09Z"
  mac: ENC[AES256_GCM,data:vUHS6ZXRGDIe72TLDqjoAZhbXU3++FKblnuWtNXfztrxbWOJVi36EJDddByCC7OUcVLq/lE6+j+epQk2H0mrJSnWVARQFN8DA/PraWghbW0LBxToSHdEmq5OwP/amgbSjUU8S1lpuBBGTjFfINAR3IEi5WRH59IOtu533cAu1uc=,iv:ccFncB/PAsCsxmkGDcJqZKcPVEj0nOyN92P42cwwloM=,tag:BDl/7yQ8f4Y3U++h4GIgAw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
