# TODO: Add n8n sensitive values, then encrypt:
#   sops -e -i kubernetes/apps/base/ai-system/n8n/app/secret-n8n-values.enc.age.yaml
#
# Key values to set:
#   N8N_ENCRYPTION_KEY - master encryption key for n8n credentials
#   DB_POSTGRESDB_PASSWORD - if using external PostgreSQL
apiVersion: v1
kind: Secret
metadata:
  name: n8n-values-secret
  namespace: ai-system
stringData:
  values.yaml: ENC[AES256_GCM,data:Cjze5n7Sa0D7VRrxDpEr3IeSXNIQ2U8NHFJt9E3ZVeqeX+5f6lznpwzhKe3IsD/b8QwrC6BO/045n6NTpUMBsMGCAzzGaIn2PQM9Seo6,iv:1aCorH1KdF8vbhgCCJ+qA2VNxVpfjGoWo/mPR15Tof8=,tag:PkAQTwjmuftzt6ZUI6VX1A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVlR1cXdXakMwU21tb2Ix
        YWRuVUJaT0RsOHNFSWViSmRnRFdvOXR6OWdRCnJZbUtiYmRDalBURFFLb0ExaVRU
        dFpKSmVCdHF0OFdBMDRTcERzUHdEa0kKLS0tIGgwQUxyeTgzTm1xZURVY1JHMzll
        TmtheDhYb2xubXViVDlWQ1FtcEIxZXMKmoEGpTTQfVOFVt+hr54ZtKPFx6SEP1pw
        i9fyQ1kVtyWrvdNkp/yIO4/nM9LRwtSyyu4NNGX3ftvF6P/UBVK1Mg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-01T03:45:38Z"
  mac: ENC[AES256_GCM,data:YfcR3wHqQMzRmZvzcPXnj4y2A/iyzqyMnk/sd5mDYWOXbrZKKBfSNAlbFrYk8jvui6UrMuruxmw+7Fn4qJiMaEy6Uf8PeNNNjM/KQacWaV+T4eiFsf4T4kA87YxD9MzgfmcS0dhZ5OOrKrCGKsF3uLw4sYvljX017Z1WLX4t6RY=,iv:5U6f5Yulnh2VG2hZHfzz/w1F9gGuy32hI0gKZ/Ifqek=,tag:idLd61DAo20tLWPPVd+YyQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
