# TODO: Add n8n sensitive values, then encrypt:
#   sops -e -i kubernetes/apps/base/ai-system/n8n/app/secret-n8n-values.enc.age.yaml
#
# Key values to set:
#   N8N_ENCRYPTION_KEY - master encryption key for n8n credentials
#   DB_POSTGRESDB_PASSWORD - if using external PostgreSQL
apiVersion: v1
kind: Secret
metadata:
  name: n8n-values-secret
  namespace: ai-system
stringData:
  values.yaml: ENC[AES256_GCM,data:cQJ2eS8Bf0pS/sXH6Hakza8HFqYItDC+oC/139A4DS6JrqOz/VnwVPOHZtS/NfThahyfX5ODSW8N09+6A4epIFT3dr3zSo3PCNS55o2WK+CLwt/nidfjdNHDRhRhb6zwzlz5s/+KMaJZ5mKhqSH8ze7Uzo4sJ8pXBrf0hCSexRcoUBJZJ1g6Ofo0,iv:MtWhkCyTk3wg8bpPu4Uk0wl/D3z/rZqIwosJMjean9c=,tag:xKdFnDYip4XmHkM4UfDIFg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVlR1cXdXakMwU21tb2Ix
        YWRuVUJaT0RsOHNFSWViSmRnRFdvOXR6OWdRCnJZbUtiYmRDalBURFFLb0ExaVRU
        dFpKSmVCdHF0OFdBMDRTcERzUHdEa0kKLS0tIGgwQUxyeTgzTm1xZURVY1JHMzll
        TmtheDhYb2xubXViVDlWQ1FtcEIxZXMKmoEGpTTQfVOFVt+hr54ZtKPFx6SEP1pw
        i9fyQ1kVtyWrvdNkp/yIO4/nM9LRwtSyyu4NNGX3ftvF6P/UBVK1Mg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-04T23:32:45Z"
  mac: ENC[AES256_GCM,data:IUllHVC5+iZfM7n55Uh3IBWxwnWlBLJYXOeNhpQ+AJvEr+eWgyeshy7bpSrDdjieXjANFlTaEdgOiBXzlTej5ABhVUC7wSeKHFOYfPSJnyU7eUsLKgNlQGOKSFfk7xRwhzMEWRxbWCewVi3FN/FgWFH7MBSlo6F5H5wzjAnJd2U=,iv:TbZ2DaPc6erC2nqTC2O8EIBdV3z1hN1LhKWaVz/o6lA=,tag:Iz0RDqiqix96e4iaC5CqtQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
