apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:X9HL3dgUldexXVGI1HygfDRJsYP77c07xhjpsfYcLfuVt5S6fIITJhCHfB0S0Dm/FNU7KUcClyV5JUZGom8r8g==,iv:QxrX3P9VwffUibKW5FlnT1n65CJ2XTZ+uU1kLuX66tQ=,tag:4IIXaH2JzydX1kxdcRqEWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUWc2amNHVDFvOTZaZWto
            OEE1c3phSTFEd3RBNGsxS3hwNEd2QTd5UVRrCmlBQ1Ridnpya3lGTzRVQzliTHlI
            U2xJVHZoY25rdFdqZEtsV3NqcHlTVTgKLS0tIFhkSlFjdHlTdk9oZ1JMc2ZaUThw
            WVZYK2V3S01nc3F3blE2NTRidWM0UlEKn9cIacVTprFh+8Oj4wiM7MfSe+pxN1nv
            aWAB0JyDPk3eXFeyFYw8CtTupkuB9i3qWx0J7ldP5ohxt0BEk4B+Lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T01:50:25Z"
    mac: ENC[AES256_GCM,data:bApfhFrqIXmLaJcQcBrNuras1+jbU4b8I8/tj9FlQIEqWVfHV5hvOXkcyTeCU26HPKKZtikej4HoSIK5J8YddKB4JSTljlhVrBXsEQnu9aPezwK7ONhTqdnIHKywP6PRkZ5rCyX4j29h/SgcTaVZKUYFlnUbvtu1ORtIP9I4bCk=,iv:h16leP/K7BAab3NZ+MgedhL7HBV4JhSXjCTWgP/+Z4I=,tag:9Gj1BAchvh621ae9pnY6WA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
