# TODO: Add any required KMCP provider credentials, then encrypt:
#   sops -e -i kubernetes/apps/base/ai-system/kmcp/app/secret-kmcp-values.enc.age.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kmcp-values-secret
  namespace: ai-system
stringData:
  values.yaml: ENC[AES256_GCM,data:AIO6,iv:DaUqjwX23CtJirgW2JSG9n3oP9uEapGmJ6KatmpIzCM=,tag:9ie+ViMf/CvCwUL0a28lvA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bXJraWQxbk5RaFlpN3dV
        Q09aY1VxZ0hNaWFpYjdpRTZ4QVhKaWZubWt3CnpMdlIzSWQrUi9RVHhyczFCS2Zs
        NndxRG9IUHMrdkVJbFRCdjlzcGFQNjgKLS0tIFlqSnd3cys5L2xIaWZPSGJqWVFI
        R0dGUWJvd1VlaDJBRlozSEx2SXhQMTAKvkLq01otzNl5k4ouiG4nvb9EMI0Y0YZ1
        2Ozkue+Y8Xb86l4IVkkhtOL39bqby7AEI6+/4H8b4Gla65gydAKqkw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-01T03:45:38Z"
  mac: ENC[AES256_GCM,data:pjeSxtrFEzq5z1+rkj6+G3Px99AEhTU/ImLMDaBrdOuZCDeE/YsN/5BY18XcbGQa0Efd4ZzlQUI7Xu/bqo1Bjq48ei+bT2bvf0LiSX3ORy3q3iii+7VCKhCOUHEYaqt+Htnp82tbHE5wu7b/sZZW1OLpEv4BBn6fEYiFxmpjMzk=,iv:m6NGDjwCudLlJ9iaMoFDg2z6ohNHIcLxfpA5OckZCX4=,tag:TtMhG5I8cmru2+rYakcmbw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
