---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sendgrid-mcp-apikey
  namespace: ai-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: sendgrid-mcp-apikey
  dataFrom:
    - extract:
        key: sendgrid
