---
apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: claude-model-config
  namespace: ai-system
spec:
  apiKeySecret: kagent-values-secret
  apiKeySecretKey: ANTHROPIC_API_KEY
  model: claude-opus-4-5-20251101
  provider: Anthropic
  anthropic: {}
