# TODO: Replace CHANGEME with your Anthropic API key, then encrypt:
#   sops -e -i kubernetes/apps/base/ai-system/kagent/app/secret-kagent-values.enc.age.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kagent-values-secret
  namespace: ai-system
stringData:
  ANTHROPIC_API_KEY: ENC[AES256_GCM,data:gBMXxN0PYNNvIckC5D/KGSefGuRwuTgfsD75wWxJ5C81pREBR/NNoD3gejzSm/4yL6jvv0/qpB3AgCNfLe6VlkhO/CNlroXgfUW5pKLomDhp41I3m5zZ3JQ/XTzDQz3cKjebUwjt5ZEet3aS,iv:8cwCmOzWtc1CG8i/nMZa0fdnA1TVfSJyVAW3ha+p/ts=,tag:GT2wSAT5K06mC3jPMfo4aQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZFg2UmNPTUpIZW1oNVVS
        amMzdWtYSmxaVTNxQUdyN29WUHNUdGdDWkVNCnFZUFEzSitiTHM2eCsyWFFqK1o2
        TGRCdjF5UkovRURkaDFFMUdBMmovK3MKLS0tIGh1SWg0aldON2RTcnpyTWxZbnFu
        RWg0YVFWQXJYMU9lOXZ4N2xiNzdYZmsKpBWMzFeh0g8gJzI1Ow9F6ZxYRUmx04KG
        XaO8d8JBYGzDWPdSbqnclgb+mwjd2/ZO7yuA6hZibsyH926njHCavA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-01T04:37:36Z"
  mac: ENC[AES256_GCM,data:66/BeIo9BU6JdCYt6qiC7EN28hEZj/wMQ7qJZnUF4GYqh+cM9VZUe8mltPp2EtooYVSEnS3J2fksC8gvTWc8xYy989riXdMLkCBDb1/aoj5kuPK6KwGn8GuesCCO/e2Tdl/QMITtoNyZjZsj2s7OSqVSUbQ9aR5U1dRckO40riQ=,iv:e/bkamNW5ZvRMwo3as1ewJQiIKSbTQolIKbVE174yrI=,tag:qi/dF695lK7ZKbpGPHIeRA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
