apiVersion: v1
kind: Secret
metadata:
  name: postgres-mcp-connection
  namespace: ai-system
stringData:
  uri: ENC[AES256_GCM,data:lYdCKQ3BWkrlcjJRaztgBne2Zt9K/mWmA9TrCrGJCnjppztD8fDSVFjQNGwJyP0NLl5qJWj+rxFOtczPfd1bnQfoboqv3FNxY8cZJVhf0fM5oq23tvfX/GQF853k4MbKVP7Rm4mJ+KUNkitGxWKtFg==,iv:k6KJmfS9hAqH/x9OaG4WjJdKc64r/XosOUSdf6S8z6Y=,tag:Bp7XBx29by075P4AA62dow==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeTZNQ0o5TG9BOVFxWUY5
        OEtLTDZFbnduZERJMGRxbWttcVZQOU11MENFCkFKb2JVRXVaY0gwWnR2RGp4Yy9x
        MG83YytHSVBmNDE1dlBCRmVYSE1mVGsKLS0tIHltZjd0eVFXK2xTbHUyeUxlRlR3
        dDRoMHpZeitSV3UvVkFueVJ5RkdsZmsKTtZhtMSUI20/Zvj/tqQSoRgmDm5altAt
        ywGWQmjeIdeHEdTa/p5WsXouJm1p0MlaJn/5PaT0msynSx6HrmPJpA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T04:43:48Z"
  mac: ENC[AES256_GCM,data:vzpGBvWmKjuxlBLvzaVaQYFddtb82UBu/kVKkVnI1ixoKwKpXJz41hDOTSz7CZYGhek4l/uHtv8vs8zdgwrrwJ8125S0Id3JbPeBveuHfuWMUGgmYWo+yiydwspstmllXJNm5E3OYwd/FSKDjYWgV6dC2q05RSnYdvbSq0rLCvY=,iv:2E4JpEKE2ctUAqy/srQ0iFpHsIaSvpu25mPrDPq0HT4=,tag:uGAMuhXlSXIdowGwqqFp3Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
