apiVersion: v1
kind: Secret
metadata:
  name: odoo-mcp-credentials
  namespace: ai-system
stringData:
  username: ENC[AES256_GCM,data:9jTv1uFDGg9o0k5dWMUe7iRLI7h+LR0Y9at/AQ==,iv:VGCY3cqW4e2sHuOlCAtv+H1IoFR2Z/ylpFiTalYMCNQ=,tag:zLv4KXpAZd0M5KYTLo/Znw==,type:str]
  password: ENC[AES256_GCM,data:NkfkSeNwOD6cuJzP+WOKdJaEhWXl2mnC,iv:bmiGcgWb2OVgEmgAWDXTHyp3qCiHp4jUuC6TbZ+DvwI=,tag:My+Zlrbujn6tvdr+HY/d2g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWTZEbHRIUW5SMk9JTjkr
        OGcwdDltUi9maHNMRFB3ZGkvWDg2UTNMNVFFCmVZa0ZHTEtzZytBeDduZWNOZ0hD
        dFc3Mnk2My9jaGhaR3d6L2s1bERaSzAKLS0tIFBFVlExRUE2aWpRdjZkS25xS0FF
        RUd1LzYwYnVVa2x5eTJIanZkWUJGdDgKAZr9A2VZy+WU+GI+N+E/3IRFvA0mHUPR
        5+cFroQjfhtUQuopDT0ubWreF3k9JaZp9zFv0dQGn4PTPiFos+dsKQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T05:52:49Z"
  mac: ENC[AES256_GCM,data:adTFfbQLIi2LC1R/JxpO+3daR1itVUpz7/sIYJH3Y1ZjVUxbJzKERrQybf9XqAu8Q1/4A7rY2MFku8no+z1B/EVUAaUGzQ62xweoGjNovBtycdoKjWy3n+3i6KmqCnQIDHenh19HyRjBt2SRocjncFj+jHNNdU5b8AIua7kX82Q=,iv:mQ2/z/oIY3cBPo1w2zqOWawxhp4GucURa3MX9eGldcc=,tag:6f/g3fk2/4uTlpE6z6J+MA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
