apiVersion: v1
kind: Secret
metadata:
  name: odoo-mcp-credentials
  namespace: ai-system
stringData:
  username: ENC[AES256_GCM,data:YcYapxIb,iv:m5JdUnu8ilRt63ZHoQA84UgGe4ySsSsgfanpmmjF414=,tag:LJBFf+caLgvZBD1W3pOhLQ==,type:str]
  password: ENC[AES256_GCM,data:FVSFw70IUvpNmKyMbgnnZD40YHFUmunwY9NHIFt2lBA=,iv:luyRUtgwtgzeOVr8yWQ1lWmtBUl8RHvhJusrUZUO8cA=,tag:tk5kQ7IIDVvxXqCnet8ATw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWTZEbHRIUW5SMk9JTjkr
        OGcwdDltUi9maHNMRFB3ZGkvWDg2UTNMNVFFCmVZa0ZHTEtzZytBeDduZWNOZ0hD
        dFc3Mnk2My9jaGhaR3d6L2s1bERaSzAKLS0tIFBFVlExRUE2aWpRdjZkS25xS0FF
        RUd1LzYwYnVVa2x5eTJIanZkWUJGdDgKAZr9A2VZy+WU+GI+N+E/3IRFvA0mHUPR
        5+cFroQjfhtUQuopDT0ubWreF3k9JaZp9zFv0dQGn4PTPiFos+dsKQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T03:14:17Z"
  mac: ENC[AES256_GCM,data:vdf3bFddJcoxNciC43FLyBeziRM6VLqk8pMPr8c5VbkeRzsgdRm5mhlTwewDJhhGeM/UxPkEB88TaVkZYfywi++jmTjQw3DT90N9rSXuBCYbUrHpJ9dH0Mb8PpWWXjxVruO6Tyxg/wvbgO6j8mf9TPWYb+AULYrdFgtS8dUxafA=,iv:lBqbnq/1zSEZGq8GxetNTLrUg1n1Jdk+An8LFcBpBto=,tag:sJFc4KIrXS7uwKz2a1eEdQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
