apiVersion: v1
kind: Secret
metadata:
  name: postgres-mcp-connection
  namespace: ai-system
stringData:
  uri: ENC[AES256_GCM,data:rGCDZTeO4rYJua+ELXEzOlAG1Ny1qLeWfHIbx5nwoVdBJtjZtlKmH/evi3HrzWVowz5bffmCxrNFHv2TThR3mxIcqaKnMjCIGX+FVgHwzRHLBwAYHYU6hIw13dY/cIxJOWCJmKoF02yquK+M9xt1RVY=,iv:nuJO6PVlgP85J987hH0ar+vAtpGo5WztNmgA09JmUDY=,tag:yeqO+3IW2YxMDDs5lJ51wA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTmJ0VTdvd1IybVkzd3lW
        RTBBSjdHeTR1d2x0SjI1bVFrUGJTTTN1bVM0CnR6THppckVBR1ZFVnN5bk9lU3dv
        SkZpWFppQmhGS0Rab0F4SHNhL3JsaUkKLS0tIHN1UkIrQTZrUi9RcndRR09CTS9P
        WEk4dCtqaDQzY2FDMlVieVBlT1ppRFkKOIRUgiY1PpCJQUuM1WYPzGYaWwfYlT0Z
        j2QO3A3k9DMfRy1SpaBQXs8J8va25NBiX8sDWcLpOOogB88jDvODcQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-11T22:50:23Z"
  mac: ENC[AES256_GCM,data:8eAha6Z6lBv00L1c0g1yZb2x6ToDPKokg2PsVH4vIPzBWBqzJ+1lm2r1LgwqAyyVbeXsCfIzf5xmoQ/it+c/Deo3Gft/8GW0LFYgGAZd0MAQJTu0gB4CQL8yFsDIx69amHbXAVn1nXdHcc332rkwIuUwM2oTizbLnpzBOWF/xmw=,iv:aoIRV/AdftJh8wUmW2OyiSXm60vf7jGrk2/XgQiJBXQ=,tag:i870KGzuKiOzFf1ffeon0Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
