# TODO: Replace CHANGEME with your Anthropic API key, then encrypt:
#   sops -e -i kubernetes/apps/base/ai-system/kagent/app/secret-kagent-values.enc.age.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kagent-values-secret
  namespace: ai-system
stringData:
  ANTHROPIC_API_KEY: ENC[AES256_GCM,data:NTwkRRTIdlZW+B9nXVm6hdVmXv6jiKerdLu5fnXT1i+99njhrwbsEKEIIrIiIVjllHQxf4emmxzwyZgOGkXsNvKRO+dHA0Gf3JMw9f1vWOcLG+aYkt6G9gzAWijv2SeHkadhjGHwzXGlCJrI,iv:FoPKy7CmniPwOV2dmLuIlR0ceJCAstHNzqJVDjiDYd0=,tag:Fd0Kq52iHOGTOFlLaqdRkA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZFg2UmNPTUpIZW1oNVVS
        amMzdWtYSmxaVTNxQUdyN29WUHNUdGdDWkVNCnFZUFEzSitiTHM2eCsyWFFqK1o2
        TGRCdjF5UkovRURkaDFFMUdBMmovK3MKLS0tIGh1SWg0aldON2RTcnpyTWxZbnFu
        RWg0YVFWQXJYMU9lOXZ4N2xiNzdYZmsKpBWMzFeh0g8gJzI1Ow9F6ZxYRUmx04KG
        XaO8d8JBYGzDWPdSbqnclgb+mwjd2/ZO7yuA6hZibsyH926njHCavA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-01T03:45:20Z"
  mac: ENC[AES256_GCM,data:vSsvkUCe3ybansXUInq8bSCCtuNl/m3tKoW8am1kl0IkFLJaNtYzDhDwuq+HB7zBqB3NnW6sMyGCGLCOrnQRIbEjUWe5zDUrYU+VluXaeHGYcaWXcnjeFO1sRKiKriXdogZy6Rg5yi8VYVWz5/p7As/Q8RHqBX9WbRcMHKSlirQ=,iv:ph1hCkPxJgBJOgEGUu4P8nJHCfxxcKrd9nDzeQpEUjo=,tag:jNgDR/UF4I11x0nLsNFJsQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
