apiVersion: v1
kind: Secret
metadata:
  name: odoo-mcp-credentials
  namespace: ai-system
stringData:
  username: ENC[AES256_GCM,data:Z0QD1aSJWUSp4+k7c0gA+G/yaYlx9VFdhbRB+A==,iv:rqlsOQKovFjagrnqWqKr9F/CjvsB334tn+94wTolEJY=,tag:JdHpCjzH5KFddtMnj5NiWQ==,type:str]
  password: ENC[AES256_GCM,data:8ZhLffM0BiwylpD4EIvMMXM44BF1+olG7eE7R1e7B+I=,iv:6Gtlg80UpcFB/+1ul0oMwwRPL0/nFYvpFhXXqhs9Zwc=,tag:Vg4mk8HgKLXXiRNbAmiPqw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYmczTXNqSURFNFNaOWE5
        SDhGTjFUU1ZRdVFrNkRwcTVNNXVOamZzTVJrClQ3SXExbktPOE1GeGNBWFdUT3dS
        MGpzSWphL3czQnBoZC84UjFrbEEzcmsKLS0tIE9YK1ZBMThuVUszdkcyVlpTS0t2
        Y21FNHlabGIvZUh0UklKemo0Rkx2cDAK9UbzTP8gXdbkENldEIQZ4cQWC5gpMVip
        GasDqwj4ZxomKWyNQKdM1ilZ223kvSsii2DQgrqAKqBojo0pz69nOg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-11T22:50:23Z"
  mac: ENC[AES256_GCM,data:PjmQIcImD9QweQGpp5I/9zcTj3Ntw+EyeZGTvQGRUGdcAACEt94O0Me52gPeJn/LD49NXliuYwKVyNfGqS+rxtJD4cJPKkh8NHn8WtwdKMR0i1H0hOlW1waumJ7pcvnYsyDYUnD0ODynfH0nSeKCJ2w1KF62/TLVrW+d95k6yUU=,iv:+XG77O8sIzZsWCOW8XqF4lKVC1ERukj+E7P/IEVWrjw=,tag:CNCRoIjDMmP27YQxvXII7Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
