---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmrepository.yaml
  - secret-cnpg-minio.enc.age.yaml
  - cnpg-cluster.yaml
  - scheduledbackup.yaml
  - helmrelease.yaml
  - secret.enc.age.yaml
  - httproute.yaml
  - securitypolicy.yaml
