apiVersion: v1
kind: Secret
metadata:
  name: roundcube-secret
  namespace: business-system
type: Opaque
stringData:
  db-password: ENC[AES256_GCM,data:xYpWpFNVppN9YF7WIzQtVfc+IATMR1Kch//2UKJ7GFE=,iv:91oI0RpxqClxsT5TX0a0Q/KyZHgKxKL9mKFp/tfKpQs=,tag:/Ywlt8TsiocMGk+q4+Etlg==,type:str]
  des-key: ENC[AES256_GCM,data:0SH2/rdwjiL2JCIeiCy/Vwlr8Wbb2XoT,iv:cWMAzFlTgRyHUBuRj3AmvCF3enMPzFVWDEpRmG/KUJM=,tag:nB9vA3N5m5tU92FRKVNReQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOHdQU2VESnR0bDBKd05j
        MkRaNkxnNXVobEV0Sjl1RjFmbSsreGtTaXk4CjJIb0p6VDJWT0ZaQmlndlZnSGlN
        NlA4RXBUVTU3a3BHc0RkVDRsZUtLYW8KLS0tIE5DQTNhSlV0MVJwVVkwVUpLcTI5
        ZWFyeXYyK0QzVXBZM3hQd044VTZtbTAKocG0r1cFAvRA/88+m2GCka60HlbXig1E
        aYzN76Pd2mOONtjWrTE2jA4IGBQATasmwE6F0j2HjSzJjdmWAI8kUg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-04T00:34:45Z"
  mac: ENC[AES256_GCM,data:Pg9TOMikSrfEohHiq8bUdsYytbONd97nTjBNtrJryWmR1mQpvH2bl23yWilAzOpXQlObqfOz/g5VznSTxToypLsoJvLWyngzWcRBXYoQovaIZiVWzO6PEHUVafEBGUbON+vBf9y6KBMjcLo15bf7NU+VXv+YNmI+KrXXwYhinbU=,iv:g0W/Mub01HhkGoJp2h2Y4f1qksIee+W6/wmxR/r8ltk=,tag:NmcUA3d8D9KGTG0mIj1/nQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
