apiVersion: v1
kind: Secret
metadata:
  name: cnpg-minio-credentials
  namespace: business-system
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:sG3fCNpmwNLGwlQ=,iv:S0/QNqalIrlPz0+RISf/siTfAgRAcbgb7POR5Q3jzkw=,tag:VALLBw9O/xu+ueQ9wPOeAg==,type:str]
  SECRET_ACCESS_KEY: ENC[AES256_GCM,data:UBcC61dnGPxU8pv0NrGN424fTpIX0NDFPZWkoKWTyBNLnFxYQuIYGA==,iv:Dmuo5v3JAX1NYAMWgaucnoizU4I3+YlJWKPxCss6xpA=,tag:kyh+moAFGFUHrIjuy7orjQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENVNxaEZrMXlBYlZrS3Zr
        Qk53Z3UwSGxNbnNrRkpBQWQ2YUg3My9lbkJnCjBSdmg0bUJCVW9adjJjNW1XalVa
        azRBOXJqbWtsajZCWXoycUV6c29iN2sKLS0tIHA2di9ROXpsQkFVajNWeUMyQ0pU
        SHkweHVlaHVzdkFLclFvREkwb1JFS2sKGnAg4nJA9IVZ7tE7CnZkwnTraPdyucLX
        ee//0Tar0knFGhQIEExLSwuATvS4zXnUkAUpxhY69oipkOzv9R+lIA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-16T23:14:38Z"
  mac: ENC[AES256_GCM,data:OgjEZ1y6pVY/ygNtVQimg5xGH0tBdgWnYItppyb4XsTIH4M06aY6aO4ABenjK7oDMAbYVZkN9UFhu6jgtli5Lc5Jbj3JLgXDkI9jiQZLeDHszAX5cZHtT5wYyEFrXSZE9TmyMULct5Z780k4O6QCjKcSc0Fw8nEA0u3b3tOmQe4=,iv:c46Ca/5RKEEG/uF7GnwpDiKKt02xrbkEnv3zAmUASVQ=,tag:dzu3si1CAFJOa3iLhWfI1w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
