# The `ingress` block tells cloudflared which local service to route incoming
# requests to. For more about ingress rules, see
# https://developers.cloudflare.com/cloudflare-one/networks/connectors/cloudflare-tunnel/do-more-with-tunnels/local-management/configuration-file/
#
# Remember, these rules route traffic from cloudflared to a local service. To route traffic
# from the internet to cloudflared, run `cloudflared tunnel route dns <tunnel> <hostname>`.
# E.g. `cloudflared tunnel route dns example-tunnel tunnel.example.com`.
---
warp-routing:
  enabled: true

tunnel: ${CLOUDFLARED_TUNNEL_ID}

credentials-file: /etc/cloudflared/credential.json

ingress:
  # Intentional deviation from upstream: fixed hostname for production gateway access.
  - hostname: api.haydenagencies.com.au
    service: tcp://kubernetes.default.svc.cluster.local:443
    originRequest:
      proxyType: socks

  # Route all external services through Envoy Gateway
  - hostname: "*.${CLUSTER_DOMAIN}"
    service: https://envoy-external.network-system.svc.cluster.local
    originRequest:
      originServerName: external.${CLUSTER_DOMAIN}
      connectTimeout: 30s
      tcpKeepAlive: 30s
      keepAliveTimeout: 90s
      keepAliveConnections: 100
      http2Origin: true

  # Catch-all rule, which responds with 404 if traffic doesn't match any of
  # the earlier rules
  - service: http_status:404
