---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: bjw-s-app-template
  namespace: business-system
spec:
  interval: 30m
  url: oci://ghcr.io/bjw-s/helm/app-template
  ref:
    tag: 3.7.3
