apiVersion: v1
kind: Secret
metadata:
  name: auntalma-mariadb-superuser
  namespace: business-system
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:WvqvyBfdKmTr6Locf+L5+sAmHYF2mrzt1FvHAdo7/A==,iv:jNOGWtOKGtWrHoDendjIJBft0NwYCrBPxDzz3lkMAak=,tag:fitZqTkGGlX2AnEZfZ4QKA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TzdIc1RCN1djc2tnNEdS
        QTZGaHl5WDdzaU95RlYzOW91ZnZNZUJsRmpVCktHN2lpRktKSTZYak9UUHpTTHZO
        UXg3ZlJSa0FBRy9IaFdzSjR4d3ByNDgKLS0tIHdBUGZXSENXcVpLczlJbVoxY05y
        SStPd29BRXlLdWlqdWVDL0RFekU0K0UKcO7aLvK9iwj/33hZpk128HehxjTiMjXe
        4eqEPWzlckzI3SJXTQ4Y5QTqoO5B1NEHCMIK8yUemldre2R0EuoTig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-19T02:57:12Z"
  mac: ENC[AES256_GCM,data:oi4kwWZkhkSK4cIXG2pX4qumHCOdc6Eckf4GyDDRgIN+Zzjr8WyhxT73Lej2rvG4yB6ie8qcStlRE8P5dgvOEZ+fZ8e347xIfgwxatyEe1r3GX2QBB/aObQluuXeRfcxhWl32jvJW8h/6OL9y3L4K8KhOeZUbsnCSkutGI7eCb0=,iv:1idyVc+A4lH9XzQco5fsEMZqmREG2iUm/wn93opukZc=,tag:MQ2z9XneZlAfCzvXMoIjzQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
