apiVersion: v1
kind: Secret
metadata:
  namespace: flux-system
  name: cluster-secrets
type: Opaque
stringData:
  PRIVATE_EMAIL: ENC[AES256_GCM,data:lwXRDQhhup1v34Wajg==,iv:uvnorEGiAbcsf+zL3xTaelVNDLvqDaBB+n6sqZEdvJo=,tag:j1yQ753mcK0fe6SqXYJ51Q==,type:str]
  GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:sTjR4lw=,iv:cF21N2tlDWqlRNo6qTpgRwUsHYrGuGegf5HPuG5mZvQ=,tag:h3jxenhQtGCbcsAWI8kfzQ==,type:str]
  POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:GEH+5Gx40J7Xc7ORl7jKeQ==,iv:lF41Vg0IbUyineAclOaTxn/wuRpJ0/qDaY9s+zbGLUw=,tag:z13wpRxYWbqAK0l3R63cAQ==,type:str]
  POSTGRES_USER_PASS: ENC[AES256_GCM,data:vEaOt5+a6S/ybK/OlfpDvQ==,iv:W9YsP/1fr5vYK5sQr9Z+m8Zg3QjGHGl/LifYJ3NWBBQ=,tag:pog2+N0ULf+YHD0TJ55MPw==,type:str]
  GITHUB_CLIENT_ID: ENC[AES256_GCM,data:uHzJLEfHXLsckoM=,iv:tYaLVeTxFGqjMrJbNv+e6tB8wMynamUGeKMP2cmEJyA=,tag:nLeVYEI3M/RjHWJraxPeoA==,type:str]
  GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:NcrYoHY8hdJc1nM=,iv:gOrD822UR3rKvhn7i6zVqf/T0H7g60R7wxLn8gfJpIA=,tag:5zEE+AVw2L0Ff6t0/obJqw==,type:str]
  DEX_SECRET: ENC[AES256_GCM,data:ZUyWUXuaVj6OQXA=,iv:XyncJ7+gVKZULFbOIK2yLOQQyIRENubiywoI+5wwZLg=,tag:C9jvHYOazh71YSZ1RMZftQ==,type:str]
  CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:51u6TZMiw5JyS2Q=,iv:V3snuRPsDYVxXQGINW3vTaOMGSDiBk7MmpCxogttazE=,tag:NxkW0bciPfQtq0xX/kRFlA==,type:str]
  CLOUDFLARE_TUNNEL_TOKEN: ENC[AES256_GCM,data:XL6ZT+OigNqjQLo=,iv:T8wdfYbZlOjl2qHwhx+BCiHNuxYR+DCY4KysuEn1oU8=,tag:bYweiaRMDSD5TjVgWwt6OQ==,type:str]
  ONEPASSWORD_CREDENTIALS: ENC[AES256_GCM,data:eVIsDWEcnYQOmrw=,iv:4hsZ2+1y+ECdMRYrwg7y8IfqdOta4tgRm8QZj+mwCXM=,tag:UtXqbIe///EOQf7+Kv6l9g==,type:str]
  ONEPASSWORD_TOKEN: ENC[AES256_GCM,data:Q21dMfXb09z7SL8=,iv:nIns0GeBl3l8Y7i9jz3FzBZyobmQ8r3jWuDomlSY9Jw=,tag:NvGkzU7XrG1L7IlX3oITWw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17xkx8ed9xl6pmtaq0vh4l68fyzjeylpx74rfuj47nq3xvr74p32quz0p7u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZXlYZ1BOb0RQQW13MVZ5
        YTV1RnRtejVzWk9sWU5NRTMrLytGck8rU2s4Cm5QSGg3ZkZBMmhRNGxTN0hoWXFJ
        RUI5QXR6K2VOT0U3S3Z2a2Z5WVkvNkEKLS0tIGw2RzRJdExzRjVwK3M5Qmw0cGZh
        bk9CcE03OG4rTlY2SU12UkFXZktDemsKFUS/uyxsXbVwLPAUieCwk8KCAWzyfOPf
        PStwQm56LATfrh2WBe0rUVDL5H7i4cM86E+UCHAa5PGPRTp4IjxiHQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-04T04:39:21Z"
  mac: ENC[AES256_GCM,data:z/NXwjUJ+9c898evlqlKtrPOCWaKqz42SaF9wxBRSnNXvQcxj4uP4pcMEcoA3H4/ycVdQbgsI9p87QsfuzDv45SH25h2YTg/QJjFcx59lJnVqhwURK/5zxq/tu2cm9W1OZAxZjw0VMO6ljab3Bks9ijZVTs3hgxFUKd88Bh0VNk=,iv:dpj4+kG8DnYpFEp3e26BYCWOxVwZpx+UiHrK0tGiiGs=,tag:kHzSJ9CKQ4arA/FFRIm84Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
