apiVersion: v1
kind: Secret
metadata:
  namespace: flux-system
  name: sops-age-secret
type: Opaque
stringData:
  age.agekey: ENC[AES256_GCM,data:HPiPQ/GcjosC8TYahmS9K2qbcdZZ31NjmSMBtYDrwB+dud8oydmfBYKmp2nnVTimtknldNhzanM2s86lf01nhR/zWa/GQMKoB7JC,iv:8FuJfpGwI9y5sHGpJ1I8PCujoGTA0cuZnf7gCRn6QbA=,tag:tenkQwwWeq7r4d6Bpt5pIA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17xkx8ed9xl6pmtaq0vh4l68fyzjeylpx74rfuj47nq3xvr74p32quz0p7u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Ky9GZDN2NXh2VlRtWkdE
        Q3JsYzQzMVNjNExSUkFld2J1aG5XelhvMzJnCmVuNjFYanNGQkxCbE53RzRJQjZR
        VW9vaWxNcVVSOGZFL2k1VGhPUXJxb0kKLS0tIGhPRlRpb0FmcG8zaUVINUh5ZmI0
        UVUxRm43eGlYK3gyaUlGV2xwQjhJalUKCQ1zRzaMDMhV6y4+7YJ7vK1SlGn+5UgN
        v9g5EAcd0YqU3UNGJtE8M6W3Eh+Avu4XbCcRrUt+exocYY5sOKnVMA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-04T04:39:13Z"
  mac: ENC[AES256_GCM,data:3vQ3Q2YzrE7bl9bP7iAuShmorEEQcS99esFtNlmsxF5UjNnE+p9Trv8ydChb3BixIr8ySohAWW4CGUpO2UrMkBkPmNB9OkI5VoRDU/cb/jSdwoh4NAPxkkE3pwA8EAJ1gVD7/qg0Bvl/UhNkZMw2sffKimVLnLHaxEDcjimvkpM=,iv:J02Xasxfv/qlFo7Y3wo1IaradingThzfqelxJdCi1UM=,tag:vUbJkxs/EP3O4GrJVMLb+w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
