---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: chatwoot-webhook
  namespace: business-system
spec:
  parentRefs:
    - name: envoy-external
      namespace: network-system
      sectionName: https
  hostnames:
    - 'chat.${CLUSTER_DOMAIN}'
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /webhooks/
        - path:
            type: PathPrefix
            value: /bot
        - path:
            type: PathPrefix
            value: /omniauth/
        - path:
            type: PathPrefix
            value: /packs/
        - path:
            type: PathPrefix
            value: /assets/
        - path:
            type: PathPrefix
            value: /vite/
        - path:
            type: PathPrefix
            value: /widget
        - path:
            type: PathPrefix
            value: /api/v1/widget/
        - path:
            type: PathPrefix
            value: /hc/
        - path:
            type: PathPrefix
            value: /api/v1/portals/
      backendRefs:
        - name: chatwoot
          port: 3000
          weight: 100
