---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - externalsecret-backup.yaml
  - secret-chatwoot-env.enc.age.yaml
  - secret-chatwoot-pg-app.enc.age.yaml
  - secret-chatwoot-pg-superuser.enc.age.yaml
  - postgres-cluster.yaml
  - scheduledbackup.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - httproute.yaml
  - httproute-admin.yaml
  - httproute-webhook.yaml
  - securitypolicy.yaml
  - probe.yaml
  - podmonitor.yaml
  - prometheusrule.yaml
  - networkpolicy.yaml
