---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: chatwoot-pg
  namespace: business-system
spec:
  namespaceSelector:
    matchNames:
      - business-system
  selector:
    matchLabels:
      cnpg.io/cluster: chatwoot-pg
  podMetricsEndpoints:
    - port: metrics
      interval: 60s
