apiVersion: v1
kind: Secret
metadata:
  name: chatwoot-env
  namespace: business-system
type: Opaque
stringData:
  #ENC[AES256_GCM,data:t5hkLLBZyfylDsnTsH53jZEwXyVHR6ENPg==,iv:NkLUVSqrfWdXoaIEqvAqbmlqAk5F0d02/XCvULHFEIk=,tag:30HNhMAlejDH71yv9h4Sug==,type:comment]
  POSTGRES_HOST: ENC[AES256_GCM,data:li8ZM7yScxsbc5iudbE=,iv:8fTK/kD+Hktt1ANnOUWfrceofmQbe4aJZmXfUWQjCKQ=,tag:wl2zoRqZQgmtG0UlkEgNgQ==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:s1j07Q==,iv:V4g/FNozR4BjQpF+E6m4+oRCl4gY7yW0D406/j5EF+0=,tag:iGonpO6IfT4ZCZROLPMKUA==,type:str]
  POSTGRES_DATABASE: ENC[AES256_GCM,data:WdRAAHfq/265fa67i85yyDg0tw==,iv:qVv5JT2SXQsOFjniTgXSHzgu9wXFRbFoVFxJZneVPvA=,tag:oNM8vFYrtAhplglPlO4QrQ==,type:str]
  POSTGRES_USERNAME: ENC[AES256_GCM,data:TgYr41Zg4B0=,iv:4eFVO27xjbjgOPO3akuWm/OcVS7qnxDlx0IVR+lzcYM=,tag:2UpExG0JL29pvfOZ2cLb/Q==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:dVPJC/nTeF/ihil+QQnZ6sdvawVY/tiICSpQ9DyzaokwVDaSKI8HYurlYCQ=,iv:sE+njhYmsdqAGvThQOLNaBTgDCAX6/PbeAnoTQhmQXs=,tag:USxFCGK13O0om1W4T3QvFg==,type:str]
  #ENC[AES256_GCM,data:y03l6oCw,iv:TiLoVW54T3CnhhMOyB2SPVPIAtB0m9/ANVnwHXDq5eo=,tag:/iPnh7aS2uOCf0wU7MWx8w==,type:comment]
  REDIS_URL: ENC[AES256_GCM,data:pgiuiQYM7DPWiK3kIufVm8r/wx9DDnceaNvUjRfv7y9Qr0uwdeOi6OTwX+jbFJraIu7Txlri,iv:dvfiYSvrTbGiMG1mYIbubjGdW09zZOveEZ9eZ21SVp4=,tag:+A4ct9khJEnKkczUMwN2wQ==,type:str]
  REDIS_PASSWORD: ""
  #ENC[AES256_GCM,data:Ekk4HaKRS97OJAAaXSx+Ne1TQkY=,iv:f/LKUIWiE8/LQYtX4c/4LkRo58D31+Yvkk2X8uEMTIo=,tag:3xuNLCgq1lEnmanInITJMQ==,type:comment]
  RAILS_ENV: ENC[AES256_GCM,data:CJJ1T6DVDsHe+Q==,iv:FHPt42uAz+kKncJwGAl0r/Rjk4FFSoiGtFHCvjJ3QKw=,tag:CH5TN7yrMfZfA+KADIzrhw==,type:str]
  RAILS_LOG_TO_STDOUT: ENC[AES256_GCM,data:1mUIrA==,iv:RNuBKG6F1hDuPx4SG0ZXIeRONa9tx6maC5CdYySTK8g=,tag:7c2y9ZsRCE4qloTIFpLyog==,type:str]
  LOG_LEVEL: ENC[AES256_GCM,data:FrDS/w==,iv:RSeDWrONSFx2xEXIarUbTFI75BtyRPLaH0ME0OD+qE0=,tag:9cdxaHVBVeRrSlOHzsM9iA==,type:str]
  SECRET_KEY_BASE: ENC[AES256_GCM,data:t9YJ/CkM5Yzfoptoe0n7i7M4oVQeu+TEZl3qmsaseNYBdQ0/yVceLXrpf70/nBqPq1hz5iSkMpxoN//IfcITFJEyTHCNmqDup9tO2nvaIqzYuRgfOEP5lSny2Yn2m5eteO9u+0y2U3GVvhvzoEzwgADmvXY+FRtjHqZCPDfJaAE=,iv:n5IWJNYzA0CdLUwEZUX8HgCxAgprBog7roU48TELMiY=,tag:88pRZl1yheFn27v8WIDljA==,type:str]
  #ENC[AES256_GCM,data:3ku/jEKXN4lA4ykp6w==,iv:AOozfCvl4f5ypzzZuN0ZZsTS62VApZutFfntNlGuC2g=,tag:s8tvX4BQt7dtCFdf2U49HQ==,type:comment]
  FRONTEND_URL: ENC[AES256_GCM,data:w9UCgmahwD7MiqU5DHxETXsGcLOMEEgqeoLkSqc2GRyd0g==,iv:Kai/5rxChSwnEUVesJ5sxgDdq0+gEhBYe+6R6b0mY40=,tag:x2m2NY2ns2laO1xYCyawSQ==,type:str]
  #ENC[AES256_GCM,data:ZBSPJyKJmGZ2c2bJEaXw44W7ixad2HLx7LF82oEu,iv:2bXlD5X5FT2uqhnYWjhQUmp86pqi7bE+aHmGZEc5yGM=,tag:FhoKCT0xbxLAnNKH4O82oQ==,type:comment]
  SMTP_ADDRESS: ENC[AES256_GCM,data:14vCYI7tyiBGnicmub5TTzc=,iv:1dWwx8jta2k4Fj2tp3MnXxm1NuR3bRkqPUx9dl+Pk0g=,tag:kWwvuPecNAQDo5XcZH8/qQ==,type:str]
  SMTP_PORT: ENC[AES256_GCM,data:ItUN,iv:iEJB2D9iiXZZnvyjH2Rv0DtNcfi79/+g9HNShUhEdbw=,tag:WtJr0pMKyoEy21NP0SJ7jA==,type:str]
  SMTP_AUTHENTICATION: ENC[AES256_GCM,data:wMGtlsU=,iv:mfFZ/fw00OnSKjCWu8Au/yMBHGdK2V25kVfiGoj6t9E=,tag:zNMfE+f3GHTf7uH6FKlk9g==,type:str]
  SMTP_ENABLE_STARTTLS_AUTO: ENC[AES256_GCM,data:hKfS7w==,iv:sa2jcno1CHJd46Lf2X9lnA8Wanvyz4yqZDm2oI3+fHc=,tag:O0O0ne7fK8KA9n+tNIiNLw==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:2KlXXscv,iv:r0RXy1z56Zw0oU8H5uZ66suXwvg+eYiFYLoam3e8syI=,tag:mIjv4b8T7DRPI1La1tPKIg==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:39VvCDRmpUbPaqlVItL82g55YLJDGvyaS1MzLXOTp2E0eBGN1hOcOhdhxRYtX4Oky2RUKLpc/WbPidjf3Pu/dbROGw5x,iv:XKEVCwq/kivw7vG4BS+l89IJGenIVn6+hr24HoicqVA=,tag:CJc7RrgJBTQjIb7xX8/9wg==,type:str]
  SMTP_DOMAIN: ENC[AES256_GCM,data:gmyNswQwiKQ+KMde3PU1HLIUiwcb,iv:CV2VrDe/WGKEfcvTiyeqisyx9khTPMcBW48vyuFcoVg=,tag:1Sg7M7hBl077q51NldJJSw==,type:str]
  MAILER_SENDER_EMAIL: ENC[AES256_GCM,data:RNQlqJ3g0Vyrbf4pcvUTYX8UwWeubu+Wo4G2M+Mx,iv:pbWAVs1tdvbjucFfznEOp0yYpx3L6JD0vtHFXyjr7Sw=,tag:Xom0DmQbNKiWH/f/J056kg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcGZQVnladTlTT3lhRU9B
        d0tVSGR1Y3NvenMweng0OEZmVzJ4U2JZU1JNCjZSZW8ycDRwR1lta3RLdFJReFRv
        SUJoNlBJcHhQUVdKaEErTm5NWFV6OWMKLS0tIDRYaWxCcVYzU2tnc1VuWUFOblo4
        TlpYNWRQL01YNStvNVY2T09ST05qUFUKselkvaIlX91dJpagdeMAbRfb/tKcnDFK
        A/mdrRU6NAGvd3T255y6mGlxr10SpPv9RfeoeZxVpl5ApyrF/Kt9tQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-20T02:34:53Z"
  mac: ENC[AES256_GCM,data:0eiYjB8bWfqPkSAzYK+w9quWFIoMPhUh+c7UnWrUayT2T7uXafo5N3Uk6S1hrgn6xO+4S3/t+2t5JpJiN7Bd6yN3O4LyR07PTgZbkZF8465YKJG0HwlI6Dpii0D4xPfK4x3MgmO1XHTEDyyls+HK57Wp7h68gwsvlqPCGZflz5U=,iv:gJA/Sr/KAV6yQD+9Dsg3t+7LXXeP6+z9QMKZN1ANVQk=,tag:jRVKqkXsM1b5W8PViACeKg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
