apiVersion: v1
kind: Secret
metadata:
  name: chatwoot-secret
  namespace: business-system
type: Opaque
stringData:
  #ENC[AES256_GCM,data:bkXiyI1PG1W8jLXWzJr1avSvOJ6s9ciKSrDnhQ62z2OY7uzkDttidh+wXrHucywKBo6VHQ==,iv:bHoWehAZhsfh9v4RuKsVfmi/6U/tsaz+dMr0xcm9dyo=,tag:PGV/uzzMuwSPKPL5aNb9rQ==,type:comment]
  POSTGRES_USERNAME: ENC[AES256_GCM,data:0gmlcpMpPW8=,iv:GmfkOpmfZQGAs0nVD+4sL5eSlW2c9Wk9ozN7dfxf+DE=,tag:D/Xf9nLg7D06GfiLfYc3uA==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:i0Krh749kp84/gVXBL4kS4JnnzxQsa1tKqHHKRyA6burihSe6+1emWjZfcY=,iv:ICnSBDfhcpky1aXzTSsbdigzfQbHLB0fX+47nuwMbkc=,tag:bWPDHwfpFxPyvczNO9DHvg==,type:str]
  #ENC[AES256_GCM,data:tOR/WradhInQsbqV3djKbjA=,iv:0X5Z/r2CW44oKr1Ue7NTTKU1obg6WdHvFNN2lubbGrs=,tag:/pnFXBlVGKkQ15IzZJmEww==,type:comment]
  SECRET_KEY_BASE: ENC[AES256_GCM,data:6sqaW08XXCy5SXkDqSNCRNV0B/vEKfSoJPbQMw3BIWjOl41jf/CPEqeGetu0BR5WNCgdl1pSB47rzgpuabe6sJOdtn2zrUb3HnGu4835xMThgm0AEzesyNJI34x9rRbphjWdVJyozXdVJYbuOGHikXTFfydjksjNiUCcoTffav4=,iv:Kd1c7IAnhaEhe8PSf+1HPc5ifIXgIAAn4vhhPIYdH80=,tag:Q+vTTX11PQ4AC2jOC+6tHA==,type:str]
  #ENC[AES256_GCM,data:HaaJl9Yx6+rO72e99Q==,iv:rsJMGKPVCrxg/+cVSiL5XyMsaL6cPnWN/a+HrYZwq1Y=,tag:iumIOH/qQXoTuDmHZ+YsJQ==,type:comment]
  FRONTEND_URL: ENC[AES256_GCM,data:09+n/gPpNOumgbuud978YPNRnYC4CLDktgLy+NVJN3jo8A==,iv:mMDLYeMGVi3zetFfiW53h3IHjxdyOMsRwmpcf0GbXfo=,tag:SiyZonda4/UQNEf4KHsTmw==,type:str]
  #ENC[AES256_GCM,data:W3wAnD6NGWZU6uhofas3FAX3FLBM6VBK36vFnjgD,iv:tkXJlY8DntBlgkojzELlQZNxt0r1wI12tZ5rkLD2+GE=,tag:Z1/1c1TqChc88ACUCL1QhQ==,type:comment]
  SMTP_ADDRESS: ENC[AES256_GCM,data:j7WIgiZhWMq+y0YguS1flug=,iv:7SB8/YT1TEW6pDpebez9wPIyexQ4cKq84L2p+ZhhxFw=,tag:3PiUlDpSfxBfYUzgtiGtzg==,type:str]
  SMTP_PORT: ENC[AES256_GCM,data:taV9,iv:/cQOVMyKfuWlvUscVjw+UctZ168wtSKr8zekTtT7bM0=,tag:YN6yh5KqD5slXsPdKTP4vA==,type:str]
  SMTP_AUTHENTICATION: ENC[AES256_GCM,data:WgkQ354=,iv:FvV6UunPQXGUHWt1ibrg7Skx02fBW38zy6sLpAu/Hao=,tag:XyFVMxiQCebfmu6Sucz3xA==,type:str]
  SMTP_ENABLE_STARTTLS_AUTO: ENC[AES256_GCM,data:EBnlsA==,iv:r7vKVSUwq+Mpcso04M2QHtUHG9VJChmyy7dZ24M0K38=,tag:zZEo1RJ0k4pMiiYerysFSg==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:rdlk/5Fd,iv:hS0WokedP+HAN2E1FU3QSvpXZwUDrQObuSZ0H+2gM8k=,tag:CgiA+/cE1TmqDUTcsyxmPQ==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:zFf+Ntu4nV1BvvRLxlxzpzBNMo8TzCX2Ee2NS6egthsuHQw/bluD9rsMtByR00DYLc1KqfBUdtR8tUoIZXBdFxsxNiMr,iv:dFGkDaGCTCgX44F3AfmGHZxl70ptPP5MwMgPjJ68bUA=,tag:fFmuY0wZcpBK0WoD2QCzLA==,type:str]
  SMTP_DOMAIN: ENC[AES256_GCM,data:sgvZIR5jbkBgiZPIcVXPbwOg/hRY,iv:84qfIUn6mzgXlpzu/WYxmNFg41pE6vspcDhnLcFfnOQ=,tag:Fmh53JXYElr9n7rzjNygPw==,type:str]
  MAILER_SENDER_EMAIL: ENC[AES256_GCM,data:9i1LS2swabwDf5cEPkc+LQ53Z4VMbRIvfJl36MpO,iv:+OzySjEbEr4COu6cSWQ1mM2bnmeb6oTxfQQZr3OItqc=,tag:D31LUvga6QSbL2bReRwI2A==,type:str]
  #ENC[AES256_GCM,data:7Jr0xV9h4pEZIV3ixvCHuW8mgK2tl65oQNl694hfDxSjPhoTQJQ=,iv:IpP6j0jp0VE9f4fi+y4Kz5F1nlJ1U6NEZv8ND01/aq4=,tag:568u1pran/Xw4vQ1r90vfg==,type:comment]
  values.yaml: ENC[AES256_GCM,data:Sg1i4p7HdZ3YjXktnJaL4kIB8Kh9brFsywMwEEoTY6Xi+Iv0q0Z6KMebzUDk/vVOamcngDT8n7u3xDBDb7bOPmoY+ewhDjo89irY86P6G7J+Vu9IQXm8kYOlq4SVHW77IUn3BPI45tpveG3OqLaXYUONiWQ1L3iFtQEtbXvj2hA7cv8rVfNWpJZoA2u0PRMhNkxpY35iugj51yUp66BszNfsNKKTEuXlB6s7OFog+afXXYFoudcM3/Olgw0fwpvvhzAKuU3Otf4JwmHLIttEkNpaY9kak9eyZeQwzAEafExxOB8tYW/5Cps4YwRR14HlfzaSyRUttJN7adAe9iXfxGe+tE6xx6HEZNP+sJQLm91sJ4sDrx7kqaJG0wK5wmmLhwoLv8PhzHoEKm3xr8knEfdBxmdMqCC2cCbxCaQ1/poRCOg6EG0LVaN0qmSfgqq+4HdfPUWgbC76VITqVwGHOB1uoSTNT8yypcmvpcRdJTg/unNQHbdY9i9vk9t9I30YUcGD7pqbcsoYZ+L/wkucgEjzydJgcdmA46ei11RVCzj1xM6TI8ZnDyf+c+b0WDWA0+kGfzZobCiCKcL7JLmcUx0TdtaP1zwjbcewRdtSyb/L+BePSrrh1oUIums+oe4kmIl++uZzwVi3V5yaZcod0ypt3vWbhVAdLE/cXgzyR6uL6Ew4xw==,iv:fKc8GC7RejDLaLXYo0jeQ8WRiyM/ooC250Qjn916IM4=,tag:lT40kfhAAC2tYhA37hINWQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ejZBTVBlekF2VXo0NzUx
        RU41OXNrMEN2Szh6SkRsS1JPWm05WDRvS25rCkJuOStjUzF3VVdZTWVBZFNDaDRI
        Zy9KWnBSQm1SWUkwSjNGS2NtZmp4SlkKLS0tIGZKK2psM3htSndINHJ6WVRKK01E
        UlZFc2dtS29XMDNpVkF3c0FQL0NCM1UKUS2VDk9cgM3St5Px/qedybLmRRelZA5S
        k1K0X8WmmDqkEk+c3VeSvtaPNpsxZHU2VADP2Ax3yPcU4O+oQEtrHQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-19T10:49:46Z"
  mac: ENC[AES256_GCM,data:WnbnYjpzJG5yiwhu5Q+vrDYJTdVxpBaw1m6+g6i80RhFZWq0MrwX5uu5v9/bUMN8/tOZzW3JyguQ5HybPpCYvzquj9EFl2MLwTXxR0dWZ1v5mpwrj0BcbcAap91jmdubG6SgPMs7j6/oW6T6Iz52hv0Q50vWBAbOfD2kJwN8vpM=,iv:JJaoGrz0IimFKMljWKok4M7ZM+ZkIB2WcZW3DlOAQRw=,tag:pW0twzlOSZNPh/wbitoCgQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
