apiVersion: v1
kind: Secret
metadata:
  name: chatwoot-secret
  namespace: business-system
type: Opaque
stringData:
  #ENC[AES256_GCM,data:4rrqDGHjmp6h+fVaLAWvyQ9ObsOsKtPbHZZRWcbZcbXfKG6GROdIHJPXc9K+vvoD1aQx5A==,iv:8Aujv62KIWbRjZe0yjMO/a3w4KmWYbndyH4GMNnEjWM=,tag:HwOy8zwVq+tm3aNoiGpVgQ==,type:comment]
  POSTGRES_USERNAME: ENC[AES256_GCM,data:5KDt2uUl50Q=,iv:ZdqcU6MsUjAiVocx0BQZ67eS7q1ORK+l1OIaYNY9EBA=,tag:r9Qf93zM/9pRBufPNZ9IMg==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:1PY/3be5cKk0yaVo3lCZSTy2HSXlo4D+iuNrMYZ9HmaaEM3ncZALNpbQ6pE=,iv:fUxTQ/GnTjT3CO5GCOH+u+MGhHJuD3dwXrP74pSPIE8=,tag:Sd7RzpAMG+TUz7fkZrERjQ==,type:str]
  #ENC[AES256_GCM,data:4aNBYcwuWVhQBM5Um/glJ/o=,iv:vBVStS/OK2mHX5bnXIbqUdeqDCK5I1IreZBVj1yXX7U=,tag:lNhwpGtJ9lbhTE5YAVYCTA==,type:comment]
  SECRET_KEY_BASE: ENC[AES256_GCM,data:yfTcNbNl+r2KUkuQE6Kz8u/m61l25MBVSuJ2diGT1a5Z5+/eIwj2cYj+++CfwQyK6nMS4J7g1hojU/ncWo9Ji2YDRzGTpcfKyPuN5LsSYqYrhmxdEBmPdS1FwW+ClfPYDwN5aHis5hzDMEI+FUS0jzUObK5I4ApronggimL0wPA=,iv:rV0tJ+dqejpwnb3pUp4Jm0MlPmIHUmWbKrEjm/RWjYo=,tag:eLqd2iQK8cK1oY3FQhKbwQ==,type:str]
  #ENC[AES256_GCM,data:y3vig0kAujJYJQxh9Q==,iv:e/EehwgMr8nKqq7dR22ak9JtOhFRsefoTyQIuRruZMs=,tag:7UX/O8o3ssqpUUYjVd8iLQ==,type:comment]
  FRONTEND_URL: ENC[AES256_GCM,data:g6B7da134L7o5UnemDlQndLQirwWlrHHz0TY8FMeM57cqw==,iv:g9G4gcLN7p9kVsAe4ICFjiKYWMq9Gh36VGv2vc8BzPE=,tag:WfKj11aEIMiE3ZuL7S2UWw==,type:str]
  #ENC[AES256_GCM,data:uU2HeHcu4mqASin07G/6KHnBdqQRBx8DhoHIMRjG,iv:M71tB2V7WWcy2YH3NdcGPbWKmVd2tXxDshlShbY8UeQ=,tag:JyyX36DNHAnLdgOic2LX7w==,type:comment]
  SMTP_ADDRESS: ENC[AES256_GCM,data:kgHDNfqksypZbQiXL+nklxc=,iv:yonaa3dYwuTYQ1P4nJ/rgo2UYoD101Sy47P5qfAGZxo=,tag:C/JdY6UF1lfOhx+/UL2lug==,type:str]
  SMTP_PORT: ENC[AES256_GCM,data:dxiR,iv:ClpqLHfzHsOB/tETAHk76vbZUXerQXs5rbmW7qGOsEo=,tag:qQrhfR3APq65RRNK+KkHXQ==,type:str]
  SMTP_AUTHENTICATION: ENC[AES256_GCM,data:+mEPmxc=,iv:53fMOxUyPKfHSrSAjOLaHtcL/KEZEts8lugHwHW2b+Y=,tag:BiAXedBLdV2JrrsN1jwPHQ==,type:str]
  SMTP_ENABLE_STARTTLS_AUTO: ENC[AES256_GCM,data:1hyBpQ==,iv:h+9CMdIdG/LzVJGr/DPvjsNn3sYRsfFxJN8z5rMoFXQ=,tag:41q+F4pn8TXP92433LbK0w==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:IMplush3,iv:S2dUKDRMb/J6tbfWp4rvBRfgMRRyA4gjm98l3oxBUqI=,tag:9eprtgd/vQvg9gmKwNPvjw==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:BywSETd6kNeLRcTcTvKqBnMMc6PjYKtO8ZEzyIL9LIX21qO1oRFB3wlqjAaWgEjj3xhl3WUjFQ6rENGegWu1Ej4TjAsd,iv:sb0nJhhkKtCog/QIPLf5ha0UTk6hZNtHgTQkhW/gg5k=,tag:RU0Yu+4aqEqAoVtLbDEV2Q==,type:str]
  SMTP_DOMAIN: ENC[AES256_GCM,data:Qv/p1f7SLcnAoXPO3rtSabfceKNH,iv:rg04top0jMyESttPiyvJsk3bdexKZinJCryiToQXVJ4=,tag:2b59uO793ENmgjf/cBNHVg==,type:str]
  MAILER_SENDER_EMAIL: ENC[AES256_GCM,data:DKRPRsBYNM2kEHet9dBFAPIfipdGwCrYNUmag+lU,iv:ac3CtziNI7Ex/R1yqGNkP5xQDAmqkqZn3WfPCIuvlA4=,tag:QOROCzPjCumSAHo9p23trw==,type:str]
  #ENC[AES256_GCM,data:/wgOYWQM8Suj/Nn8fiu6O+U0sJC7dVyc2N43VkksLQRcnMxl1As=,iv:QjhisHQ4DWsg8d3Dm74eA0AwELdxQKBHrdA68phNrh4=,tag:JKCHCpGIKTJ6wAHdxyuLBA==,type:comment]
  values.yaml: ENC[AES256_GCM,data:mEQcfbSkIyKZVFfHn/W7M9EbUmiXtuxoLs0V0UXKsYFJHYlXzOAsDYhsfkX//p8Iu9nXFbTuigrAYExz1HMi57p7CLASj5T9sOu4aB+VOMgdX8u1xRbU7Qm5gXzpq5pJIdqUoaU1+KVeP86np8z516pSdC6dWIpXilYN/WzQVKHCp61noX5ED9rp6zZY97HcdYl09kSNv2FiOURsZtTrPPcIyfEGclqMBKcpHCjAuYx0NJFv5kRcZ/zg//H6MLAv2OJW0SgEkRCt7JIkgMmrU6r66FhGbZV9T3WZgXWGNch7pcJi52kt+snwa0kFPyEY89PEkC3fgWhCGLCDMs2a7aa8qlVBXotWY4KqI7TmtPSV2jmTEzeofzK72kOE+IrFerAe6V5zYmboEZ6B,iv:RPADoayThr5JIQRcOufvcrAO6qGLhp1y4sRhumkCzYk=,tag:eyCvGoDoo3yewsZMgp+rIg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VlY4bXkydTZuWTV5R0Ry
        VUMwS1AxMzl5RkRLUUpNRXNzTE94eXJaaldNCjd3ZHIxczhkbUh1UHN4bDRBdTNT
        bDF6b2pBd1g1eTB1eE1sT2ZWY3Q4eVEKLS0tIERpQ1ZwQU1wcjdtN0F5cFlLUk9r
        M2RjN2l1R2ZyYUo3endlcUxUSWRSeGsKxzb6RDcBqwndgaG23cjTnSUKp608oGHr
        WHIQOA3cbCoBZxut8T/XnVAJuA31Q2oyL+C8ikTERMJW2EMCZefX3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-19T09:51:59Z"
  mac: ENC[AES256_GCM,data:VB+0xf802MdCgmvEWwc0TWANPgvM77HACjLZPD+elRjfmw5RQ103ELFpWcvaQNACsEY7Um9wxTSqXvXQU3FEiV9Q6r5zGjdQMMQHl0vPML0qANXEj5gjjDITUadQvL36dWP+eT6ifq9NGFvxMTnR/1ZtJmGi1eRGNTZa+PxY08w=,iv:Ge/CnZdJ1GhK4M/+ClW9xZ0eVD5rOLBD2tIDsKqq/so=,tag:rZeHkNhn5X8qvju+qdZp7w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
