apiVersion: v1
kind: Secret
metadata:
  name: chatwoot-secret
  namespace: business-system
type: Opaque
stringData:
  #ENC[AES256_GCM,data:jl5mS7Ep97GeuRQOZVyVRkVaO825/Jo9x/ftToWBAq8c/rrbqhWY0LjAG82JKjPm9f0COg==,iv:ZnHSxXyXWvR+IiTmNsgnktusQceP9I7BXxcEmSd6jZ4=,tag:uF7YvKnUP8wfVIx153tcvg==,type:comment]
  POSTGRES_USERNAME: ENC[AES256_GCM,data:jroOxCqnKS8=,iv:cmMEv7U/+T2qqRstaqABuv7h8PLHgN6y/kV0yY8oxBQ=,tag:W96dhU4bHkig4rmNnGKgPQ==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:6hGyWvNXBcR6ZR/Xl/dx3PdjWyeJ0BaAsJSqR52cdJz6ftGKfRjCS0sJm5A=,iv:jL8Q6llMUEQx0bYca21ZaJJsDDcY8bU8aCWCOFqFkcI=,tag:SKE/MlAHiD2zzuHF0ZksIg==,type:str]
  #ENC[AES256_GCM,data:v4WIT1SWxSOh3/2smkj/R5w=,iv:axgStfJ9LILJhh3eZVgp0zwfykSrXETjpz0V0AfuVPo=,tag:NZIJe+E5JvNdxveLkGFdQA==,type:comment]
  SECRET_KEY_BASE: ENC[AES256_GCM,data:Jh8CwVzgj/w7z3hZTMiTU6VcmXHMb/epIgw/s1Wbt/qceyL3YHO7rkTzwiaeOVVMraBitG5u7onytStKS9TWTFfy8n0ZvMCAnQeHsm+h9rM68jjHSWndtaVsV5lAsgqEDCixy5ZUg1H1MjyJWt+JIQisMSCA4+g3bdpGPSag8qw=,iv:eSQe5ttrBHOAqx7dUKuLTH8y2gAx/siPNoOo1TH6iyA=,tag:wcdpUec83nfXNtitYe4BDA==,type:str]
  #ENC[AES256_GCM,data:sevjeFi1X93ug8+DMA==,iv:hdeg8wFKjAM0pj95h2FN+8fzU3kHiLqeJD1d0XbH8MQ=,tag:UA8eKuTWqUFMuJNd9Ue1dg==,type:comment]
  FRONTEND_URL: ENC[AES256_GCM,data:YH4Rygy/vVkL8HI4E9iO/muqcGqYySyRMcyoVXf8DYBR1g==,iv:ZfryWWDv1zDLGngpINe4yDhmNdkylxxaKRCTFIylbeo=,tag:NYpO2FPuLtNEeWqnYcN7eg==,type:str]
  #ENC[AES256_GCM,data:gS3pk6ePWeQTVOp4PBJ41eDWlru8BS+jlWX7KqC3,iv:KrTq8HTsS8XNc3/wpREuynw52UtRp8f09KOESholVbg=,tag:XV1RcL6ix2py47ZK0x0eeA==,type:comment]
  SMTP_ADDRESS: ENC[AES256_GCM,data:wq6UAcbp4l6Ru3oG85EPl9w=,iv:2lM49qcXmWhuwEB3wwmBiAd7PqEbBwO8gKVsXRr8cOI=,tag:SyfYydfrs6TQssYF4gKNhA==,type:str]
  SMTP_PORT: ENC[AES256_GCM,data:yEf+,iv:g6NlRA6NavSY5g8ymrjLuZN+8WLGjAPxin1h/pQsqlU=,tag:H0JBeyQ2qtn1nxeJMDoXbw==,type:str]
  SMTP_AUTHENTICATION: ENC[AES256_GCM,data:s+0HoPI=,iv:UDTtdqOLUPhzK0oX6/qoiewvfB/i/ClxN28/Bi86npI=,tag:48g8DfJTJi6c9cGx0wzOOw==,type:str]
  SMTP_ENABLE_STARTTLS_AUTO: ENC[AES256_GCM,data:Xp8W7w==,iv:S78WcFmbQGLxWlgsGQEZtfyMDqLh1tAbH4P7Vk4UdB4=,tag:bgZvEx4QBzERnRm1KMaHkA==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:uuQtgOlx,iv:+gCOw8CDPpuUf6zsRDHq2flW7WAHIGw9E5TlwQbSKK4=,tag:gy/+bpMNKiFJfJ0sydU62w==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:TktpzD+JE1AeNzEQ35qWRVEYeNURG8Qy9XdQu4T4NBcT2EOUAf2qAvdHdjneTSOvI5mtY4SY3oTiXNqJrj4Bqv+T8Nm4,iv:np0IBl0ZrOwkvtrke4ausl4JGMKFME9HVy9bz7lMd9U=,tag:NG+Cdr+07w6DBYhOdOHXJQ==,type:str]
  SMTP_DOMAIN: ENC[AES256_GCM,data:Oxs22SZ6Q0U82aivDjFk06wxOzzD,iv:ZrECAE+6iu7Z4p4JZre2QcF3ArxPKCvsqJr9ZwFXxMQ=,tag:E0cAGpAhSV5l1qMlGub+Kg==,type:str]
  MAILER_SENDER_EMAIL: ENC[AES256_GCM,data:X9UpEIpN5kDyuQXCSWAIGcsrdLb6Pqu3pMQGqez2,iv:EDCIm9j0ZhXmLb1v07yWYmHGU30MziVMDWbbILiYAH8=,tag:3thV6M2CRCq5HEJUVdTmWw==,type:str]
  #ENC[AES256_GCM,data:NsGVkUBOHtN9wIh5qCfgeAeeNfJIEC6VeGg2juIKhvDhmHTUcL0=,iv:tnxiUvo5z5e4I1E5Zycq6iq0nZBx7OWjhN5X1Ip2jqg=,tag:ApDjLjqgfbiQDmMI5YyhNw==,type:comment]
  values.yaml: ENC[AES256_GCM,data:0sNwTnpRJ+vBR12DkpPEj5pD5GpVyU/DVqddpRprxf+XipvzXVvmJdefGBhsruzGDiNDDfH+OpPXjMiGP78iraEoGugyQo9CP0L9pB+rPaHvy1PLprOhee1/bolmpNIPggXJ4cRUtQ0jN7UK0wD1TWP4uzvfnEh4HFeufLhb220au1S5X+WfZkG4T4//EXXsKXXA+EmSSxh5wDzucWF/I22dPe3tUVJytHK1Uf33FonyjE0l4ub0Uh5b6OZ80mKBrF8lp51LUfLC193O5tIZCLmcthWvAbHAx7LzBpWzngODvPd1bKKvVwtQh8PTsOBUEZt/OAujdGSi8nqgl6k2pIlgNzUgZf/UOsWIiACtozEpHB+wJj03paGMvRFdwwktKcmC/jSSquYvOfvqBZ27hveaEZwrfD7P5pK7pYPmgMEkVw5kibvQf5r3THWA0lhvZ3zbdy3/ZGCHQlPToaKDQd3WHKyNCoK5zxCIwGLfsWQ0XYqyQxf63le0FVkQI/uognks4TWp+gdWA1BWp7hGe7Hoe7+IskYPMd/TDldUbNNf8GP4FJ2NJON/mNo0HgOzLNUbfXNZiAqFSsf2VA==,iv:/qN6y+xuQneXYM+yGqjqrxaTITq2AlOZmI9/LQd/JoU=,tag:OE2Aiw78KWRtVt80RVdWjw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySmNrbjlvZGpXZ0VZeWtt
        L3RMQ3lySjFIK2NNSkpmcWZuOG9VWnMxblI4CkJWOVp2ZGNQQlJoSUd5Q2U1MTJ2
        OGlkdndpRXd6U1lUTVJSMU9MUjB6MnMKLS0tIG83Y2lJZFZqNUFDMk90QUhaeFB3
        dk1JaHpYQjBWZG9LdThLeDV3aDFEY0kKYkkad5I4IHe4uI3OV3nCnjobaSki2Laq
        MKLduSomFjXCjDTQLSps9DQDrQiJIIw8vahdpgmIVBrsnFGswMuODQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-19T10:45:13Z"
  mac: ENC[AES256_GCM,data:R9WOZ3Tg7mOGDPAWtDrmDVEkW4TlLiXZIS6HD0ITChtAjY5vDcspcSaa3eAplvqtqPFZhnsNL8LxJ09YhxzdE/XBIrAMblTWsQarQC932QQ+0joWIA1UPFA9BGetGN4JzyfSXF2SbEBy/r9cNNY1Xso6nN5teqy94O/sYbMHiKM=,iv:noPQAa8Rb3aXWAFK/dMCP9M7eFfwQVYe9Ivua2PdI5k=,tag:JSC/saQFUOQLNZN09/Fr/Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
