apiVersion: v1
kind: Secret
metadata:
  name: chatwoot-pg-app
  namespace: business-system
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:9vt0L+73OTk=,iv:XusO7G5Plv0rHzCGJwdYlWY1KlFqNhyEKWoWjW2e69g=,tag:m6JTcqaJrC9DPIR6Ytn/Cg==,type:str]
  password: ENC[AES256_GCM,data:4nUv9UDG1ITdxfjXEy/89NPZDdCnCmA7JWrxxKwz/Vlv2ohmP2NBjJBFpzk=,iv:fBFHBmx27kwrFFukRLxrDua68auRL3/YfIS/JGWjfME=,tag:tnPA/iEFwh3BorYSmXLw8w==,type:str]
  dbname: ENC[AES256_GCM,data:7KUTR6u/YSH6MW10WNj4aKvpAw==,iv:gr7oU0OnDd2cOZtf4sVWBV+Pq4+2pBA/2aOAti/DX/o=,tag:+xdENA7ClJRC5gxf/6/G4Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TUpDZTVEd0JjVGdySitx
        bE1PL2Njd2ZHYlpDb2VaSkpLRzQ1WktPSFFBCk0rNEhpN3dzcm1TS3MwZnkwUE82
        Wmd2MldlaWlqOXk5S0lLR2JCbnRRM28KLS0tIHcxamhoOTRJY0c3Z3ZLd2UySE01
        VnQ3OUhheklSVTc2bFd1bTVNSVhleUkK4OPUk5EThrmQXVpKGIzVt2aQ6fFXrmdL
        X/8FtWYHLt0bEkV3nA1HpsZqyAbF37mhyrmgwGDwGfoqmP6+lATPVQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-19T09:51:59Z"
  mac: ENC[AES256_GCM,data:arvHqIQ4CfSJJO5i2fJyOa6xrYXkBaZnpUVymaJixd9AYBNNEtSPUUxY0jIf5Kr9IB7G1COSqwzhgWtTtryQbiW5Kfba/JoL6om87+w8q7WNSuPYEowaAumfKVbJHHerox+zdz5xpJGMqCf0L5lNQseAsYobBTG81klm+W0/8nc=,iv:rL+BJRuMEu0PjReUqldRotq5xx4O6eAfg9MqclmNH1s=,tag:GfbaydaUMed+z3s/yOhZ9w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
