apiVersion: v1
kind: Secret
metadata:
  name: chatwoot-pg-superuser
  namespace: business-system
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:dXxUyv6Bkbg=,iv:Lcx228ZudAyf7k7ZLfJMub+maachpsYA1sEYBz9ymDo=,tag:S2Ik+/Fam8W8ypAqMFFaLw==,type:str]
  password: ENC[AES256_GCM,data:hiPT9UOvhm1TaFtMR5LvVe8dKEaZMccVJ4/hWxnf7D8Z8ciLVgM0hJwjYuA=,iv:0yCZVvmjOZP2oCSZXQUTxJweQMLsapqewgKFJbviaQ0=,tag:4EJK9cA3/8H/uG+6GViqqQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbGk0ZmN6bFZCSWtaanE3
        cGFybnJLR1h3R3JpSTNQcFZWMWtPeU1UOUdZCi9XTzhrazRPcXUydjI2Yy90Qzhw
        NmhFazY3MHBEYVd3U3k2eTVOZjl0UGsKLS0tIHA4TE9WTEk5VWdnQldCYlA3QkRU
        emltWmlLMWlJTC9IUDkzK250L0YrWDAKdPzbgv94fDGJGHUuxusnmy+3SF1xaLUt
        MXBrL2cCDFI6S2x68Xwyp5bXbXLLi5Fs/IWhDtU2THhmc80NGJA3Jg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-19T09:51:59Z"
  mac: ENC[AES256_GCM,data:b9ojmAcJjxwina27w01cXcl0mCDtPk5+VqLULUfEgJGP2z73gdP3ti407k+F8YeEVeCYCztBbkFUY6Hw3j6DVTjvJ+FTeoddBJuxSYOa0eRj11dTJ3TuEpQOTQ8MSEGx9hMPuP2L/DRlNjkOtNIR9vd4xAkclM0EPpwTOsaN+NA=,iv:2vKLqahzOxEKCspByvP219L4iZpUJBYQaiwC0h7XHvw=,tag:a/m7xbmbbIPAgKOnOQUDhA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
