apiVersion: v1
kind: Secret
metadata:
  name: driver-config
  namespace: democratic-csi
type: Opaque
stringData:
  driver-config-file.yaml: ENC[AES256_GCM,data:+ishMJ0llb/O8ujbOdVEpsg5UhMTyHmgYYQQtNjg7url81d2JWLx+Qx45fwfdLDSCXXjRJLHQbNlFgCRAo+x+TmIYue1fP/u4T7LuGuFPXS/AGxnFTssgPtsAuTjbEffjuFP7tkIxdXd+Uj6Pm7SmOXxh1CQr6ZpECSrgjMVx6BbAowq4pbMsoLfLD+/8VyyuwWTZJ8PVo2bgH15zXbd0/Npqw80NuBdgA+AKy0LDjjoxredLewAqyx5IaZCJOE33jICcRnqrlttW/5el6jhBNe9VQ/nIJTdY1qtQK9cyOl6sLU4j2B3xtEShmwAst85TKN3+598Exe1ppiTjFoUY6p04miJ62fqSNrrG1ot+QWRrjbEmfh3aTlDhePmkv8TaiHe/8b8lgLPDVehTjDhlupf+pcGJ7D1+JnPvA8FNSMYz1Jc5lzvgB7c5nD2zXAgS1WInpSTf/WXGCUKWK0aToRf/oPvxLI3JHKwlna3/jiFjDcfeVTuAVEec4ErVKmn9//X0J2jppDDxVkWh9RIbxcoH3FSlUCSjLuKEC1FWBwn1JNJhRMjrCjLX6PTao898jsdpeoqBgn3/IPfKirv8GstWslsDHvrn9f2Djrd5XhKnNt3zi2dhN1nh+fWeDKFdMhE/+n1eLl/YsB560vvRXJiEC0JAQvabDQyLlsSixGCT3eayLlBX/jAlqSN27dbotz0QsQj9ZIjDktRMXcedxoq5GcXnYqtKFiq9ZjN9NFmpAQTemRjTqelN3u5c0vbWQyAyFRba/ozcCmd+3QuVXTia08WZu8aMYhl98VOQiUz2rO54mwsdmHSHnSa+NTLOKqCBDw9QWIRFISMvG0OTHNTkq2yQ3Yr3PSr18pTifvd6QAO9ZXgb6Bmsp6oyP5h5V2bneV61BfxaBjyYh3SfnQdbp67HuXt/bvN6iCMEsiFowtaAuNRwYyrLTP7UmiGpgSVQ7QAsCc/B85QcmAFtc3cafPoWBSQYcwP+ltu6JqugA==,iv:zjFp/7BF/OKCvfO2bjb2RUMrZ79yFJfdpA+H4RCdSMA=,tag:tn7c5WZ6ssJe3k2BytWYig==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SFV1RDBwU21wQU9jeks1
        ak5NZk9NUFY4MjZIL1ZLWGYzN2M2SE5rZGdZClFQS0NoRUFoWVdVeEtPd25EaWhU
        SWtVTU42RnpyVFNYQ25CWUE1ZndkQW8KLS0tIDYrVlVGV3AxdG5MUXRJYUxaYmVP
        QkQzWWtvR2NwTEtYbCtmZncyWit3aDgKBjFJzkAJKNYPKTjK8TOPCvvUk7nlHYUr
        cI4w1l/s+dOw1XiMG2WC1grwuGYK3UJyXYcr8fJG/zPbexBrHLBELQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-07T03:13:46Z"
  mac: ENC[AES256_GCM,data:K0KzBGDCVpjiLyZva51ky6dpig09q3+5RZmPjWIydP3ViU0xaaQVtZPkDiBoJh0ozOlQNsc4DmPbzqO64N4zeu2QhlMBeW4vwoNObs8RYACXNezMNO13m4EnlTbTxy4GN+gAosAxFhdI27uLLwmNBbQUW3wY90sXp2kHw2qRxWE=,iv:5zaNwP5+eVye3rBgBRNrVR6EJ1Peq9qkZs2NKzHe5xM=,tag:TsBrP5RaI6C+K+0tl4mFxA==,type:str]
  pgp:
    - created_at: "2026-01-07T03:13:46Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQGMA8h3Ifv2u/MMAQv+OKygSFRaSbJsrxSo6bFnzcuOf0xWAFGRn+DsQD3KqafB
        2gyzDxAqD+ZHR5u5chaRj4yBqnFW3MJGZSR8Uf9HJCheszna9qi4O6tbnn3wwBGZ
        27Zywc235TDohPw4/rJJxYmaLHRcUDjZhNupe20Czs4BWyaIjzOCm07BiouZmyak
        mtqIGIbB9KJTtzQ8jBJFJy3q6zQ9MsDLRtJn0iLwsmVTYHIVjNX6/cntnYw+xMOL
        EXLYHOusgfo4lkbu2Sdk047bsuGi5GV7uHRBuL0ie6rnJBT+WBdBxvt/2/JnFDj/
        WCdsc8uBFqTLcoQDLwy2zgqAVyyq6NhyHrAGC3ImGQiXRhsGLf9H6haMJ0p9e3IH
        O3F3GNDRt1GECWovCR68wp+gLinPLDh/Do1c9BLU4OQO5viHTPUUGgFyXgGQm0/l
        yqLkTfF7CuiSim/ArjdsQGFczVZ4R4rrSyASeCilmvrchxYLeMENkxVwE0+iiA+e
        S2aj65YL58ylOoG0IpCV1GYBCQIQ86msGEL1h0n+g6l0CeA+Jxi9yuCr3YHXzDWv
        h6H6lFYLYMM7RPtL9qqSDRvvEl3y8uQAdc3QxjcHNpD7tid5nELpg6iV+FjLXpJC
        OkYrSOF4my2MZ0OHmmZYyvfRdE+fdR0=
        =hWMG
        -----END PGP MESSAGE-----
      fp: 67AF5B5A73800481D8E41667C87721FBF6BBF30C
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
