apiVersion: v1
kind: Secret
metadata:
  name: driver-config
  namespace: democratic-csi
type: Opaque
stringData:
  driver-config-file.yaml: ENC[AES256_GCM,data:t7x5jXi0J/nW3flnUOMudoD4EiD3MevAjr7iZDkMT3ja64PoDZdarslVwAJUSgmSzApP5CCWt4DiTlYyuyo/O8bKC9iBNhebZLPw2pjUeN/wdy4RKYM6wrAoVv8kI+AV84xZ0ysxoXYX5XKbBDDTMY7ul/RuID+U9hrLYR8MdPhWzYwyQnUMcSOoZyA26Mdito7NJrf7cIEN9Ki8gOtOGtkNsf8LZF0eCjZp9pUfs5hXHSGQIW0LWwY0PExUXWrSr2xoijbmdWZZ8G8QO2UA/7FbJP9NHYIjYlmWgGqcTqG76rMKT3m0SrJlrIYzAOchj/aoHenRFnM3yTUjO4MuIYDWTcNb8OGdFBb+a4jd+83xY5qvAl29Rmkn94dALtFGbJrbZIsiEHU1EK+bebn+BaxOQwx/YI48IITFqd400e3rrXBfh6Mk4mIszpxEPUgZjJ5gqllJfgu74OWQyEWJCUCTSwzzQoFRCO27QN0lHqPW35SnepO+6fMGMhgvQxOta8ulbgGzCR9HfN3Poe7S99xnVtz59jmXdxhKPuN6nfuk8upsgvMWYQkDkcZzIeuwVBWRpDAKX2lW4NsXmQ+3htlmEXX/Dk8cAWvVNFve2TjzKKplKnDk2WUEQY7MFyrAsAAxrF+NQ3di9svrL6wiMLRAN4jW5aOTiIV9ggetu9iX58Yghrn7gN2oGUsH4s3s+DUNATqeeYn1bemQzn9K7C1cj/Dzp78aWmC3v/C+eP1IhJHKa2J8Bj6NdpzGuyhXrBz7mpc79YpUSAkgVk5sTXZTRqoEosfjQTKWsqMrQNyyyX4CtYP0oIyB6ttK/FLonsMzCZkE3P6veNkGyXH5RSTtv1hopCRcHmQu6gkmvSnzH87Tm/1dyFGDQds=,iv:vS9xmkTImUyxj+WkzOpbY9dgZgVaOOd9cOMizWpnpD0=,tag:Agfm6wOQBgkeOyOLruBStQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbjhFanMzdHFscmNvZWN4
        M3YrQkpUT0xxclpBeW03Z2h3ei8rK2ZQQlZrCkRHUVUrS0lVWFc0Sk11S2trODNr
        K2xqR1hXVTl3anBJSUc1QzUranI1dDQKLS0tIHJ4Q3AvMkdXR1huS0JDckNjVFFQ
        R0xFR2o4QlRWUUYyT3JOaXZoUmVsWEUK+qQqK8qYRtEx5flkLzHoMZX5V6/rKWyv
        OO7o+aueSWEiRFXpZqxHMcNCHCnBvC6PXOpmYeS4PJILNpSf262GoA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-07T01:49:53Z"
  mac: ENC[AES256_GCM,data:lB0BGFq7ckJhVOaN/cQebERVpu9KaxZwKlYuPSbIFG86RC4XeSczeHiexJ8pgjkyDbh9omAsiFIsbWJt6yZ+n6y3FcZmqnFzeBGQn2sponcoPNJWx16KiBFEY0ubKrWRpk70Hf4skAcHASQp5hvdGriSty+/cgSwg7fMNbIkvqg=,iv:hMBz9RgfHHUoXS2a4G/zolOAW1UqO+OkDvO7muXXLmI=,tag:CasBSIjcQwi04qovMb4tjw==,type:str]
  pgp:
    - created_at: "2026-01-07T01:49:53Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQGMA8h3Ifv2u/MMAQv/XoqeXro+dAkw7YdTLbpZpdf1p4XaBDhFdoV4c/+RHMUX
        YNX/RLMpwx+S3IOs8phqifDXBZLo3XgdbHfqZZUHkIC+V31uV+Z8LWuQXqB5dyqx
        yJFAFEiyazzOfRrBeurGt0RIdK7MvryHWvfWzs/twHSGWrBY61/wwPgGiuhYsddB
        7QZMylJ37vNc0v7M5GGykrD98mIUqBy5ukjD882kegzKbijlX96of5yBinbHvcoY
        xo+XynMnaflpCA+uJnWf6+kQne+8W5WfqNAq2f6YO7LWE7g70rinc6XjtFBPECtC
        xHzZrmBgjnyJ3YNNlPqO/e1HKOzJlPZlT3KiTcAe0oFrMiQXHOU8Qy5tNLKT/oyW
        /acQYWbZSjbX9ots6Hn2yhkOAbE4CC5+BOhblDQ6/UnMN7MUulpo59BopnlwvTNP
        xIhgGkwVaVhG6LLnUonl50Evh3x+V2CteqlTZYjvNr0rKGOqL0GKoKftYMjcqbBt
        7M0mKpsgetI/EDc7/u2w1GYBCQIQU22GmX+RCdTkK2RXfTdEVDYdZLznUhiQkyiX
        J76loXWf3RcBO+KKGgRl3lGj5fIbnwCWTTDvhiD6moSLHM6RkuRnC+3cWyVmydK1
        56iyadGvAOM07F1WowWhqPIq0dq0mK8=
        =SNIB
        -----END PGP MESSAGE-----
      fp: 67AF5B5A73800481D8E41667C87721FBF6BBF30C
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
