apiVersion: v1
kind: Secret
metadata:
  name: driver-config
  namespace: democratic-csi
type: Opaque
stringData:
  driver-config-file.yaml: ENC[AES256_GCM,data:ngRnjl+yWP6y2rrfBvrx6cDFuUq6BWpGhswAYOabJzlhPF6cmMZZBIizDAfyPKtkV5ZjJ/IuxYxhjExEhVHajThfofhFWMQ2fsdBkXeVRS+S2vNcqH55+nSnQnGZ73ERbbc02E203NjHxiHO7yNXq5otPIjrkKL3OdBQn+qDTTHaHdOwvdgJ0vN2TibmTQo69WsZRobO11mqejifue2sX5h+0ngBHT4HvoS0ECUSnkf8ByN6MM7b0TvtWZPC1oj8jmgJU8mfaU8dFrfCAZwe7oL/M//GHLj3Z1f6ppk3i5xIdxgZ6f4t7R2mc7nGoHrtyuCPlSWjTwbkf6vLU21qJ8IP1evHvy8YnjowbeSZSE8zD5+zoZ2TBMuPDzGNO1QWb1qn066C5U8Wu+dDRshegB1vPJr23IkdAPGFobnT01zfq6qlB5Kg1fghStH9zW6McJrDupPnKRi9I3kppuZwywE+dlSbc+EFmRsT3zoyejXEZOvmBaTzYpHuYZwypIQTjg1N01LMDvz6dSVrNMQrqsN1ckKE4Wm/lbnMgXq0k23TCpApZuSfaUp+ILOLkTb1VoimONL83a/xJTTtUNJ4f1Gm44N4AvGGkjWj+jBmLX1jEBLE0oWgLcssP1sjTh8N9Vd3ue+jTLZFirNR9P7IrhGsARJB2A5bqb5G6KPow6y6BxGxhDOtBBL19d+l48nEfqAOvwaTsLICez+YmD7zMkcfzDGna7SkAlA07vZRZy2SNr/v1n49k7HoA0txePCWQdBW8gm6OZ0EgVnrHvz6TSmM1a3NTq7xSJDNhRBifK+fqB9/S7DHiTecAOgU1xFlTFxL+TPfnecc7FqjVUnvKkkrL8SH6L3Y0Q==,iv:W1mg4m+6N1IGwW+1jSZS00ajHH0mGZiqw3+Cgiuq0tg=,tag:fqQlO8TGjWu5MIlhQ1Bwfg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ha5rkmrmdgd079xkvlp3svelhgd3wxm9l0v88es7hjp6ujcvnyjsxxrc7h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0c2tXVjBwQzFuYTFOTW1u
        WlhvK0NiUDFxcFRodGcxTHhSYkFhRnROVUhNCkN2U1FldkRHNkZ3NzBSVkFuWVd3
        WElBYjU4Zm1FaWxrUXZiSGdENnFTUncKLS0tIGMzcDBLbkpJYklkYWd6a0dJbmVY
        YlNEdWNEa0tuaDJrOVoremkveXpEWVkKYwS7EE/wITRX0520FdC/rHAjC/HEzsI9
        +WWS6NvVEDqc/1ya9XfzdWudYNKnjaawooqDvof8Y4L27URlohoE9g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-07T03:10:00Z"
  mac: ENC[AES256_GCM,data:HmVqXPGUxzXuAhdDEIcG+VMEIgtO/hNwH8JKyMV+R/mv7rhPuEL0Vb3Q+OvDjOzfS/GesWRvfns5Y68anDYgyKnBDJYoBpvhCwdVj57+M47dX9V1LylUVZ+5YHF4IRyOwzDQl57Sgx8H9mhZPRKSle29GSEoWcWy2qUKyilJctU=,iv:OoS6tSXH7jMXGsbKi2tqjN7KqII26Qi9tRYUVMqZaAA=,tag:P87QCAr0UbHqS0DkDTYlfg==,type:str]
  pgp:
    - created_at: "2026-01-07T03:10:00Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQGMA8h3Ifv2u/MMAQv9EFfM+ECJ3Jl/v2Ho4AgRlBdtingVf/nIpvroDDltlbEE
        /OO/Rf7Gun2YvUEhFzKuDbi89G7jV9bzzHD8ar/dT+JQEqJqKkQyWDLhE3Z7JPHg
        SQUQv0m5oEkMDrt8AWHvJ3HdjKbxZnKZtgwz0EPRQwoIo51+uT8UCPEZBgcFQMJh
        NkRdCEVQpz9j0Ki3Z/gzS2ecCerDm1zlep9bPPZdz1p28vRf9wQYd60NeFyCFszy
        wVaNbrTuTiKdPZnXdenw06BiktYGkneM5MXmz7QmZJ+BU1QNEBhPPtOty+SgvCRF
        Tu+TuKq4fmhsSZ5dQeEJGvyuaAK/smIbBfKGfvPJYdu/B7z6ZR93GrfLasgteuYY
        /a5JYtUSwHz+HpwZ8OEzpB6A6lwEc5jD+wJj4g6AkNE2yL07pdxUuZ7TrOOOK1tZ
        QLBCppGjuui5wOkVS3GNidXIiEhAsbH+IZIdEsemqo2LU9Iz7mZ95sV6S85aKEYX
        w1KqKOxFeZasGtZ3lg1z1GYBCQIQXL2GJHMex2Ptc+6RsNq12xx01LGM+mOmgLvb
        jSWXsifniv7wFUqab6MaWrfbxDDQ2MoTyjP5I9b3Pnwa0W7iVsDORycGerijjJX5
        uf7oaHBn2Ou5JRQAQ7tOG8oH1qAP5Rg=
        =Q/79
        -----END PGP MESSAGE-----
      fp: 67AF5B5A73800481D8E41667C87721FBF6BBF30C
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
