---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: business-system

components:
  - ../../../components/common

resources:
  - namespace.yaml
  - nextcloud/ks.yaml
  - onlyoffice/ks.yaml
  - auntalma-elasticsearch/ks.yaml
  - auntalma-rabbitmq/ks.yaml
  - auntalma-magento2/ks.yaml
  - chatwoot/ks.yaml
