---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-oauth2-proxy-httproute-refs
  namespace: network-system
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: business-system
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: business-system-staging
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: home-system
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: ai-system
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: observability
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: kube-system
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: volsync-system
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: security-system
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: development
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: kguardian
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: network-system
  to:
    - group: ""
      kind: Service
      name: oauth2-proxy
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-oauth2-proxy-securitypolicy-refs
  namespace: network-system
spec:
  from:
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: business-system
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: business-system-staging
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: ai-system
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: home-system
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: observability
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: kube-system
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: volsync-system
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: security-system
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: development
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: kguardian
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: network-system
  to:
    - group: ""
      kind: Service
      name: oauth2-proxy
